pom.xml
release.properties
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/resources/templates/tagOverview.vm
src/main/resources/templates/tagReport.vm
src/test/java/net/masterthought/cucumber/StepTest.java
src/test/resources/net/masterthought/cucumber/no_step_results.json

The css class step-duration was missing in the tagReport template.

Add the missing css class for step duration in tagReport.vm

---

src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/test/java/net/masterthought/cucumber/ElementTest.java
src/test/java/net/masterthought/cucumber/FeatureTest.java

Tags are hyperlinked in feature and tag report for easy navigation.

Hyperlink tag names in feature report

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java

The version should be taken from somewhere instead of being hardcoded in the Java file.

Updated VERSION variable to the latest version

---

src/main/java/net/masterthought/cucumber/Background.java
src/main/java/net/masterthought/cucumber/ConfigurationOptions.java
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/ScenarioTag.java
src/main/java/net/masterthought/cucumber/TagObject.java
src/main/java/net/masterthought/cucumber/charts/FlashChartBuilder.java
src/main/java/net/masterthought/cucumber/charts/JsChartUtil.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/util/Status.java
src/main/java/net/masterthought/cucumber/util/StatusCounter.java
src/main/java/net/masterthought/cucumber/util/UnzipUtils.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/main/resources/templates/errorPage.vm
src/main/resources/templates/featureOverview.vm
src/main/resources/templates/featureReport.vm
src/main/resources/templates/tableHeader.vm
src/main/resources/templates/tableHeaderParallel.vm
src/main/resources/templates/tagOverview.vm
src/main/resources/templates/tagReport.vm
src/test/java/net/masterthought/cucumber/ElementTest.java
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/JsChartUtilTest.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/StepTest.java

- Merged duplicated code into loops
- Reduced code complexity, increased scalability
- Moved Status to public type (separate file)
- Linked page footer to github project
- Replaces number of counters with Map that keeps all values in single instance and allow to extend for new one
- Updated tests so they don't mix skipped and pending results
- Updated colors so Skipped/Pending/Undefined/Missing use the same yellow background color
- each chart presents all kind of results (not only pass/fail)
- fixed colors so they are the same on each page and chart
- updated some tests to make them deterministic and simpler
Issue #76

- Reduced number of generic Exceptions

---

src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/StepTest.java

Gherkin syntax is not properly HTML escaped

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/ScenarioTag.java
src/main/java/net/masterthought/cucumber/TagObject.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Result.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java

- additional clean-up
Issue #90

- screenshots are now presented for missing statuses

---

src/main/resources/templates/errorPage.vm
src/main/resources/templates/featureOverview.vm
src/main/resources/templates/featureReport.vm
src/main/resources/templates/headers.html
src/main/resources/templates/tagOverview.vm
src/main/resources/templates/tagReport.vm

- moved html headers (META section) to separate file

---

src/main/java/net/masterthought/cucumber/charts/FlashChartBuilder.java
src/main/java/net/masterthought/cucumber/generators/TagOverviewPage.java
src/main/java/net/masterthought/cucumber/util/Status.java

- Extracted duplicated code to separate method

- fixed chart colors for Skipped and Missing

---

.travis.yml

As described here:  http://docs.travis-ci.com/user/workers/container-based-infrastructure/,
build will startup faster.

Routing  build to container-based infrastructure

---

.travis.yml
pom.xml

This tool (as of now) works better then the Python version, which I'll be upgrading soon.
Thank you :)

Use Codecov global uploader

---

README.md

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/129%23issuecomment-129129525%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/129%23discussion_r36585674%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/129%23discussion_r36585675%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/129%23issuecomment-129129525%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6078.31%25%60%5Cn%3E%20Merging%20%2A%2A%23129%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60a45e5fd%60%5D%5B3%5D%5 …

Added proper link to code coverage

---

src/main/java/net/masterthought/cucumber/generators/FeatureOverviewPage.java

This fixes regression from 3bb467a0b4c3b390e81ccc181535e0f0b85bb8ee,
which cause flash charts not render properly.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/132%23issuecomment-130537119%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/132%23issuecomment-130537119%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6084.10%25%60%5Cn%3E%20Merging%20%2A%2A%23132%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B5.79%25%2A%2A%20as%20of%20%5B%609cb6654%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%2 …

fix flash chart reggresion on FeatureOverviewPage 

---

README.md
src/main/resources/templates/footer.vm

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/134%23issuecomment-131108490%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/134%23issuecomment-131108490%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6084.10%25%60%5Cn%3E%20Merging%20%2A%2A%23134%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%6053be6fb%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%23134%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Renamed links and use new root repo: https://github.com/damianszczepanik/cucumber-reporting

---

pom.xml
src/main/java/net/masterthought/cucumber/ReportBuilder.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/135%23issuecomment-131496063%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/135%23issuecomment-131496063%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6084.10%25%60%5Cn%3E%20Merging%20%2A%2A%23135%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60d051c15%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%23135%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Released 0.2.1

---

README.md
pom.xml

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/137%23issuecomment-131519578%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/137%23issuecomment-131519578%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.60%25%60%5Cn%3E%20Merging%20%2A%2A%23137%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%6084e8e78%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%23137%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Upgraded dependency to newer versions

---

.travis.yml
README.md

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/138%23issuecomment-131542694%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/138%23issuecomment-131542694%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.60%25%60%5Cn%3E%20Merging%20%2A%2A%23138%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%606ef0cf3%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%23138%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Integrating project with scan.coverity.com

---

.gitignore
.travis.yml
README.md

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/140%23issuecomment-131873182%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/140%23issuecomment-131873182%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.60%25%60%5Cn%3E%20Merging%20%2A%2A%23140%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60ecaf53a%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%23140%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Readme update

---

.travis.yml

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/139?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/139'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Launch coverity from master

---

pom.xml

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/142?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/142'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Updated pom dependencies that have no impact for tests

---

src/test/java/net/masterthought/cucumber/ReportBuilderTest.java

I've added checking of flash charts' data in ReportBuilderTest
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/143%23issuecomment-132064083%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/143%23issuecomment-132064083%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.60%25%60%5Cn%3E%20Merging%20%2A%2A%23143%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%6016d91e6%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%23143%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D …

improved ReportBuilderTest

---

src/main/resources/templates/topMenu.vm

#133
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/149?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/149'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Added link to the top menu link that drives to the last build on Jenkins

---

src/main/java/net/masterthought/cucumber/charts/FlashChartBuilder.java

use StringBuilder instead of StringBuffer
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/150%23issuecomment-132373869%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/150%23issuecomment-132373869%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.41%25%60%5Cn%3E%20Merging%20%2A%2A%23150%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60e48f8ab%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23150%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

use StringBuilder instead of StringBuffer in FlashChartBuilder

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/generators/ErrorPage.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/resources/templates/pages/errorPage.vm

Issue #90
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/151%23issuecomment-133644798%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/151%23issuecomment-133644798%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.44%25%60%5Cn%3E%20Merging%20%2A%2A%23151%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.03%25%2A%2A%20as%20of%20%5B%60b272371%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23151%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Added info about json files when crash is detected

---

src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/main/resources/templates/summaryOverview.vm
src/main/resources/templates/summaryReport.vm

Issue #148
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/153%23issuecomment-133647913%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/153%23issuecomment-133647913%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.44%25%60%5Cn%3E%20Merging%20%2A%2A%23153%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60a6a3f42%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23153%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Fixed summary description for Step page

---

src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/TagObject.java
src/main/java/net/masterthought/cucumber/generators/TagOverviewPage.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java

Issue #26 
Now scenarios are compared by id, not by name
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/155%23issuecomment-133737415%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/155%23issuecomment-133737415%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.65%25%60%5Cn%3E%20Merging%20%2A%2A%23155%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.79%25%2A%2A%20as%20of%20%5B%604e792fa%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23155%20%20%20diff%20%40%40%5Cn …

Scenarios with the same name were not counted properly

---

pom.xml
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/156%23issuecomment-133752659%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/156%23issuecomment-133752659%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.93%25%60%5Cn%3E%20Merging%20%2A%2A%23156%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%608d7919a%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23156%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Upgraded gson dependency

---

pom.xml
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java

maven-source-plugin 2.2.1 -> 2.4
maven-javadoc-plugin 2.9.1 -> 2.10.3
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/157%23issuecomment-133797785%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/157%23issuecomment-133797785%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.93%25%60%5Cn%3E%20Merging%20%2A%2A%23157%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60b339d03%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23157%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3 …

jsoup 1.7.2 -> 1.8.3

---

src/main/java/net/masterthought/cucumber/Artifact.java
src/main/java/net/masterthought/cucumber/ArtifactProcessor.java
src/main/java/net/masterthought/cucumber/ConfigurationOptions.java
src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/json/DocString.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Hook.java
src/main/java/net/masterthought/cucumber/json/Match.java
src/main/java/net/masterthought/cucumber/json/Result.java
src/main/java/net/masterthought/cucumber/json/Row.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/Tag.java
src/main/java/net/masterthought/cucumber/json/support/ResultsWithMatch.java
src/main/java/net/masterthought/cucumber/json/support/ScenarioResults.java
src/main/java/net/masterthought/cucumber/json/support/StepResults.java
src/test/java/net/masterthought/cucumber/ArtifactProcessorTest.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/RowTest.java

Moved not-report files from json package to support
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/158?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/158'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Make attributes final and public without getters

---

.travis.yml
README.md

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/160?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/160'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fixed support for Coverity

---

.travis.yml

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/161%23issuecomment-135532729%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/161%23issuecomment-135532729%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.83%25%60%5Cn%3E%20Merging%20%2A%2A%23161%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%603b4b09e%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23161%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Fices incorrect secure token for Coverity

---

.travis.yml
src/main/java/net/masterthought/cucumber/json/Embedded.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/test/java/net/masterthought/cucumber/StepTest.java
src/test/resources/net/masterthought/cucumber/embedded_image.json

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/163?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/163'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Added support for different type of attachments/embedded content

---

.travis.yml

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/162?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/162'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fixes coverity secure token

---

pom.xml
src/main/java/net/masterthought/cucumber/ReportBuilder.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/164?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/164'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Released 0.3.0

---

pom.xml
src/main/java/net/masterthought/cucumber/ReportBuilder.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/165?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/165'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Preparing for next iteration

---

src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/tagReport.vm
src/test/java/net/masterthought/cucumber/StepTest.java
src/test/resources/net/masterthought/cucumber/project1.json

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/166?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/166'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Step output is formatted in template instead of json file

---

.travis.yml

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/167%23issuecomment-135971736%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/167%23issuecomment-135971736%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.18%25%60%5Cn%3E%20Merging%20%2A%2A%23167%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.35%25%2A%2A%20as%20of%20%5B%60c262932%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23167%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Switched off coverity scanning on master due to the plugin problem

---

src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/ScenarioTag.java
src/main/java/net/masterthought/cucumber/TagObject.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/tagReport.vm
src/test/java/net/masterthought/cucumber/DocStringTest.java
src/test/java/net/masterthought/cucumber/ElementTest.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/RowTest.java
src/test/java/net/masterthought/cucumber/StepTest.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/168?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/168'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Eliminated potential NPE from Element by making model immutable

---

src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Tag.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/test/java/net/masterthought/cucumber/ElementTest.java
src/test/java/net/masterthought/cucumber/FeatureTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/169%23issuecomment-135976368%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/169%23issuecomment-135976368%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.07%25%60%5Cn%3E%20Merging%20%2A%2A%23169%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.16%25%2A%2A%20as%20of%20%5B%6073e9f0a%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23169%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Tags are hold as Tag instead of pure String

---

pom.xml
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/test/java/net/masterthought/cucumber/JsChartUtilTest.java

https://code.google.com/p/guava-libraries/wiki/MapMakerMigrationhttps://code.google.com/p/guava-libraries/wiki/MapMakerMigration
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/170%23issuecomment-136004069%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/170%23issuecomment-136004069%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.06%25%60%5Cn%3E%20Merging%20%2A%2A%23170%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.01%25%2A%2A%20as%20of%20%5B%605ad73d5%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%2 …

Removed guava dependency due the following problem when releasing jenkins plugin

---

src/main/java/net/masterthought/cucumber/TagObject.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/resources/net/masterthought/cucumber/docstring.json

https://github.com/damianszczepanik/cucumber-reporting-jenkins/issues/108
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/173%23issuecomment-136501230%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/173%23issuecomment-136501230%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.66%25%60%5Cn%3E%20Merging%20%2A%2A%23173%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60c5897d2%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23173%20%20%20diff%20%40%40%5Cn%3D%3D% …

Crash when tag contains ":" in its name

---

.travis.yml

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/172%23issuecomment-136502623%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/172%23issuecomment-136502623%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.66%25%60%5Cn%3E%20Merging%20%2A%2A%23172%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60692fa62%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23172%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Build Coverity from master

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportInformation.java

Fixes damianszczepanik/cucumber-reporting-jenkins/issues/95
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/179%23issuecomment-138006156%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/179%23issuecomment-138006156%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.61%25%60%5Cn%3E%20Merging%20%2A%2A%23179%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.04%25%2A%2A%20as%20of%20%5B%6062c28db%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23179%20%20%20diff%20%40%40% …

If step does not define match it means that method was not matched with the step and step should be marked as undefined

---

src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/resources/net/masterthought/cucumber/project1.json

#39
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/180%23issuecomment-138103522%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/180%23issuecomment-138103522%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.63%25%60%5Cn%3E%20Merging%20%2A%2A%23180%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.02%25%2A%2A%20as%20of%20%5B%60a083429%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23180%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Feature file name is mapped from uri without loosing first part

---

pom.xml
src/main/java/net/masterthought/cucumber/json/Row.java

Issue #182
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/183%23issuecomment-139043668%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/183%23issuecomment-139043668%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.56%25%60%5Cn%3E%20Merging%20%2A%2A%23183%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.07%25%2A%2A%20as%20of%20%5B%6052c3c62%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23183%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Regression in data table

---

src/main/java/net/masterthought/cucumber/StepObject.java
src/main/java/net/masterthought/cucumber/json/DocString.java
src/main/java/net/masterthought/cucumber/json/Element.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/184%23issuecomment-139049175%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/184%23issuecomment-139049175%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.42%25%60%5Cn%3E%20Merging%20%2A%2A%23184%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.14%25%2A%2A%20as%20of%20%5B%6035d4e93%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23184%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Fixed violations reported by Coverity

---

pom.xml
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/resources/styles/reporting.css
src/main/resources/templates/pages/featureReport.vm
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/StepTest.java
src/test/resources/net/masterthought/cucumber/project1.json
src/test/resources/net/masterthought/cucumber/project2.json
src/test/resources/net/masterthought/cucumber/project3.json

damianszczepanik/cucumber-reporting-jenkins/issues/132
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/188%23issuecomment-139751472%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/188%23issuecomment-139751472%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.45%25%60%5Cn%3E%20Merging%20%2A%2A%23188%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.03%25%2A%2A%20as%20of%20%5B%60ea0933e%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23188%20%20%20diff%20%40%40%5Cn …

Fixed problem with double array for output attribute

---

src/main/java/net/masterthought/cucumber/json/Feature.java
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java

Issue #176
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/190%23issuecomment-141700147%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/190%23issuecomment-141700147%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6085.93%25%60%5Cn%3E%20Merging%20%2A%2A%23190%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.07%25%2A%2A%20as%20of%20%5B%60a4026e9%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23190%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Device name is equal to file name without path and extension

---

src/main/java/net/masterthought/cucumber/Background.java
src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/charts/FlashChartBuilder.java
src/main/java/net/masterthought/cucumber/charts/JsChartUtil.java
src/main/java/net/masterthought/cucumber/generators/StepOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagReportPage.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/support/ScenarioTag.java
src/main/java/net/masterthought/cucumber/json/support/Status.java
src/main/java/net/masterthought/cucumber/json/support/StatusCounter.java
src/main/java/net/masterthought/cucumber/json/support/StepObject.java
src/main/java/net/masterthought/cucumber/json/support/StepResults.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/test/java/net/masterthought/cucumber/ElementTest.java
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/JsChartUtilTest.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/StepTest.java
src/test/java/net/masterthought/cucumber/TagsTest.java

Reused method from Apache library instead of own implementation
Moved classes to different packages and sorted by purpose
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/193%23issuecomment-141755687%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/193%23issuecomment-141755687%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.50%25%60%5Cn%3E%20Merging%20%2A%2A%23193%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.15%25%2A%2A%20as%20of%20%5B%60e9fcafb%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20% …

Reused method from Apache library instead of own implementation

---

src/main/java/net/masterthought/cucumber/Background.java
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/generators/FeatureReportPage.java
src/main/java/net/masterthought/cucumber/generators/TagOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagReportPage.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Scenario.java
src/main/java/net/masterthought/cucumber/json/support/ScenarioTag.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/main/resources/templates/pages/tagOverview.vm
src/test/java/net/masterthought/cucumber/DocStringTest.java
src/test/java/net/masterthought/cucumber/ElementTest.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/RowTest.java
src/test/java/net/masterthought/cucumber/StepTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/195%23issuecomment-141813848%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/195%23issuecomment-141813848%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.26%25%60%5Cn%3E%20Merging%20%2A%2A%23195%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.85%25%2A%2A%20as%20of%20%5B%60b58413e%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23195%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Removed unused collections

---

src/test/java/net/masterthought/cucumber/DocStringTest.java
src/test/java/net/masterthought/cucumber/ElementTest.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/ReportParserTest.java
src/test/java/net/masterthought/cucumber/RowTest.java
src/test/java/net/masterthought/cucumber/StepTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/196%23issuecomment-142515562%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/196%23issuecomment-142515562%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.26%25%60%5Cn%3E%20Merging%20%2A%2A%23196%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%606122329%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23196%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Changed depracated matcher 'is(Class)' to 'isA(Class)'

---

src/main/java/net/masterthought/cucumber/json/Embedded.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/199%23issuecomment-142723026%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/199%23issuecomment-142723026%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.10%25%60%5Cn%3E%20Merging%20%2A%2A%23199%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.16%25%2A%2A%20as%20of%20%5B%60ff95185%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%23199%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Fixed handling of bmp embeddings (issue #197)

---

src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/tableHeader.vm
src/main/resources/templates/tableSorter.vm

issue #203
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/205%23issuecomment-146662130%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/205%23issuecomment-146662130%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.54%25%60%5Cn%3E%20Merging%20%2A%2A%23205%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60a3aef70%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23205%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Table sorting on Feature Overview and Tag Overview

---

src/main/java/net/masterthought/cucumber/json/Scenario.java
src/test/java/net/masterthought/cucumber/ElementTest.java

Issue damianszczepanik/cucumber-reporting-jenkins/issues/142
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/207%23issuecomment-149675557%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/207%23issuecomment-149675557%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.19%25%60%5Cn%3E%20Merging%20%2A%2A%23207%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.35%25%2A%2A%20as%20of%20%5B%608448afe%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23207%20%20%20diff%20%40%40 …

Backgrounds are calculated as Scenario

---

src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/211%23issuecomment-154362848%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/211%23issuecomment-154362848%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.61%25%60%5Cn%3E%20Merging%20%2A%2A%23211%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60b1d87ef%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23211%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Revert base href from pull #209 that breaks chart loading

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/resources/templates/footer.vm

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/212%23issuecomment-154366511%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/212%23issuecomment-154366511%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.60%25%60%5Cn%3E%20Merging%20%2A%2A%23212%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.01%25%2A%2A%20as%20of%20%5B%601ad3c62%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%23212%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Removed version from the app (left in pom.xml) to make upgrading easier

---

.travis.yml
pom.xml
src/main/java/net/masterthought/cucumber/json/Embedded.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/213%23issuecomment-154369389%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/213%23issuecomment-154369389%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.60%25%60%5Cn%3E%20Merging%20%2A%2A%23213%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60d75baab%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%23213%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Upgraded library and add full verification against JDK8 by travis

---

src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/json/support/ScenarioTag.java
src/main/resources/templates/pages/tagReport.vm

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/220%23issuecomment-155764575%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/220%23issuecomment-155764575%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.87%25%60%5Cn%3E%20Merging%20%2A%2A%23220%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%608548886%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23220%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Fixes regression related to wrong link to feature file

---

README.md
src/main/java/net/masterthought/cucumber/json/support/ScenarioTag.java
src/main/resources/templates/pages/tagReport.vm

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/222?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/222'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Updated README.md after API changed

---

pom.xml

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/224?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/224'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Updated joda-time version

---

src/main/java/net/masterthought/cucumber/ReportParser.java

Issue #218
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/226%23issuecomment-156533011%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/226%23issuecomment-156533011%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.33%25%60%5Cn%3E%20Merging%20%2A%2A%23226%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.07%25%2A%2A%20as%20of%20%5B%6044f65e0%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23226%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

IO stream was not closed at all

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/generators/FeatureReportPage.java
src/test/java/net/masterthought/cucumber/DocStringTest.java
src/test/java/net/masterthought/cucumber/ElementTest.java
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/ReportParserTest.java
src/test/java/net/masterthought/cucumber/RowTest.java
src/test/java/net/masterthought/cucumber/StatusesTest.java
src/test/java/net/masterthought/cucumber/StepTest.java
src/test/java/net/masterthought/cucumber/TagsTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/227%23issuecomment-156721978%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/227%23issuecomment-156721978%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.25%25%60%5Cn%3E%20Merging%20%2A%2A%23227%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.08%25%2A%2A%20as%20of%20%5B%605ae00f9%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23227%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

ReportInformation stored list of features in two objects

---

src/main/java/net/masterthought/cucumber/json/Scenario.java

Issue #122
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/230?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/230'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Cound scenario status once

---

src/main/java/net/masterthought/cucumber/json/DocString.java
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/resources/net/masterthought/cucumber/project1.json

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/233%23issuecomment-158181754%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/233%23issuecomment-158181754%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.28%25%60%5Cn%3E%20Merging%20%2A%2A%23233%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.09%25%2A%2A%20as%20of%20%5B%60927ad69%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23233%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Fixed coverity issue and improved code coverage

---

src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Scenario.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/support/Status.java
src/test/java/net/masterthought/cucumber/ScenarioTest.java

- elements from json are mapped to scenarios attribute
- moved html code out of Status class
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/234%23issuecomment-158525304%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/234%23issuecomment-158525304%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.37%25%60%5Cn%3E%20Merging%20%2A%2A%23234%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.18%25%2A%2A%20as%20of%20%5B%606dc77d1%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20 …

Code clean-up

---

src/main/java/net/masterthought/cucumber/json/DocString.java
src/main/java/net/masterthought/cucumber/json/Scenario.java
src/main/java/net/masterthought/cucumber/json/Step.java

Issue #122
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/235%23issuecomment-158620014%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/235%23issuecomment-158620014%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.63%25%60%5Cn%3E%20Merging%20%2A%2A%23235%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.44%25%2A%2A%20as%20of%20%5B%60680a811%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23235%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3 …

Optimalize Step class

---

src/main/java/net/masterthought/cucumber/json/Scenario.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/tagReport.vm
src/test/java/net/masterthought/cucumber/DocStringTest.java
src/test/java/net/masterthought/cucumber/StepTest.java

- removed unreachable code
Issue #122
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/236%23issuecomment-158736845%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/236%23issuecomment-158736845%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.06%25%60%5Cn%3E%20Merging%20%2A%2A%23236%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.87%25%2A%2A%20as%20of%20%5B%60c274ef8%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23236%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3 …

Optimalize Step class - part II

---

src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/json/Scenario.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/test/java/net/masterthought/cucumber/TagsTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/239%23issuecomment-159348597%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/239%23issuecomment-159348597%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.14%25%60%5Cn%3E%20Merging%20%2A%2A%23239%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.17%25%2A%2A%20as%20of%20%5B%60265e499%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23239%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Fixed problems related to hashing

---

src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java

Issue #122
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/240%23issuecomment-159625234%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/240%23issuecomment-159625234%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.02%25%60%5Cn%3E%20Merging%20%2A%2A%23240%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-1.12%25%2A%2A%20as%20of%20%5B%603a7b388%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23240%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Reduced triple loop to single one. Recovered some scenarios with tag that were missed previously.

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportParserTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/242%23issuecomment-159988951%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/242%23issuecomment-159988951%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.07%25%60%5Cn%3E%20Merging%20%2A%2A%23242%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.05%25%2A%2A%20as%20of%20%5B%60fa5a06e%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23242%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Fails the report on every feature file which is not valid json file

---

src/main/java/net/masterthought/cucumber/ReportInformation.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/243%23issuecomment-159990765%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/243%23issuecomment-159990765%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.98%25%60%5Cn%3E%20Merging%20%2A%2A%23243%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.09%25%2A%2A%20as%20of%20%5B%60de484a2%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23243%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Merged steps iteration with features

---

src/main/java/net/masterthought/cucumber/Background.java
src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Scenario.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/resources/net/masterthought/cucumber/project3.json

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/244%23issuecomment-160288524%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/244%23issuecomment-160288524%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.07%25%60%5Cn%3E%20Merging%20%2A%2A%23244%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.04%25%2A%2A%20as%20of%20%5B%6052fb88a%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23244%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Tags are counted properly for scenarios

---

src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/json/support/StatusCounter.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/245%23issuecomment-160390722%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/245%23issuecomment-160390722%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.04%25%60%5Cn%3E%20Merging%20%2A%2A%23245%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.03%25%2A%2A%20as%20of%20%5B%606244092%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23245%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Counters for total steps/scenarios/tags are delegated into StatusCounter

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/json/DocString.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/ScenarioTest.java
src/test/resources/net/masterthought/cucumber/project1.json

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/247%23issuecomment-160695681%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/247%23issuecomment-160695681%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.30%25%60%5Cn%3E%20Merging%20%2A%2A%23247%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.27%25%2A%2A%20as%20of%20%5B%60ebb21d8%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%23247%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Added tests to improve code coverage

---

src/main/resources/templates/footer.vm

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/249?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/249'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Cut off bottom margin. Added links.

---

src/main/java/net/masterthought/cucumber/json/Embedded.java
src/main/java/net/masterthought/cucumber/json/Hook.java
src/main/java/net/masterthought/cucumber/json/Scenario.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/support/ResultsWithMatch.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/tagReport.vm
src/test/java/net/masterthought/cucumber/StatusesTest.java
src/test/java/net/masterthought/cucumber/StepTest.java

Issue https://github.com/damianszczepanik/cucumber-reporting-jenkins/issues/149
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/250?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/250'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Embedded from hooks @before and @after

---

src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/resources/templates/pages/stepOverview.vm

Issue #254
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/257?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/257'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Steps without location are not displayed on Step overview page

---

src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/generators/StepOverviewPage.java
src/main/resources/templates/pages/stepOverview.vm

https://github.com/damianszczepanik/cucumber-reporting-jenkins/issues/145
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/259?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/259'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Step overview shows average duration

---

src/main/java/net/masterthought/cucumber/generators/StepOverviewPage.java
src/main/java/net/masterthought/cucumber/json/Scenario.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/util/Util.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/260?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/260'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fixes issues found by Coverity Scan

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java

https://github.com/jenkinsci/cucumber-reports-plugin/issues/5#issuecomment-163906583
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/262?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/262'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

If build crashes hasBuildPassed should not fail with NPE

---

src/main/java/net/masterthought/cucumber/json/Step.java

Issue #263
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/264?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/264'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

@Before and @After steps do not provide name

---

src/main/java/net/masterthought/cucumber/json/Step.java

Issue #263, Pull #264
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/266?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/266'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Remove 'unknown name' label for steps that have no name.

---

pom.xml

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/267?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/267'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Updated dependencies in pom.xml

---

pom.xml
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/charts/JsChartUtil.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/main/resources/log4j2.properties
src/test/java/net/masterthought/cucumber/FileReaderUtil.java
src/test/resources/cucumber.properties
src/test/resources/log4j2.properties

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/269?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/269'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Supress annoying messages in test mode by passing logs via log4j v2

---

LICENCE

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/270?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/270'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Added info about license

---

.travis.yml

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/261?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/261'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Build fails with openjdk7

---

README.md

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/272%23issuecomment-165567853%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/272%23issuecomment-165567853%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.98%25%60%5Cn%3E%20Merging%20%2A%2A%23272%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60293bc77%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23272%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Added new shileds

---

src/main/java/net/masterthought/cucumber/util/Util.java
src/main/resources/styles/reporting.css
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/StepTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/273%23issuecomment-166751609%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/273%23issuecomment-166751609%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.00%25%60%5Cn%3E%20Merging%20%2A%2A%23273%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.02%25%2A%2A%20as%20of%20%5B%60ed16046%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%23273%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Improved UX of error message expand/collapse functionality

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/generators/FeatureOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/FeatureReportPage.java
src/main/java/net/masterthought/cucumber/generators/StepOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagReportPage.java
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/main/resources/templates/topMenu.vm
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/ReportParserTest.java
src/test/java/net/masterthought/cucumber/TagsTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/279%23issuecomment-168238563%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/279%23issuecomment-168238563%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.98%25%60%5Cn%3E%20Merging%20%2A%2A%23279%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.02%25%2A%2A%20as%20of%20%5B%608af86a3%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23279%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Unified methods and attributes

---

src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/generators/FeatureReportPage.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/main/resources/styles/reporting.css
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/test/java/net/masterthought/cucumber/DocStringTest.java
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/RowTest.java
src/test/java/net/masterthought/cucumber/ScenarioTest.java
src/test/java/net/masterthought/cucumber/StepTest.java
src/test/java/net/masterthought/cucumber/TagsTest.java

jenkinsci/cucumber-reports-plugin/issues/8
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/280%23issuecomment-168259102%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/280%23issuecomment-168259102%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.35%25%60%5Cn%3E%20Merging%20%2A%2A%23280%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.07%25%2A%2A%20as%20of%20%5B%60363d805%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23280%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D …

Background were counted as scenarios.

---

src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/json/Feature.java

Pull #175
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/283%23issuecomment-169265567%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/283%23issuecomment-169265567%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.38%25%60%5Cn%3E%20Merging%20%2A%2A%23283%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.03%25%2A%2A%20as%20of%20%5B%60db69952%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23283%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

The same feature can be reported in different json files

---

README.md

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/286%23issuecomment-170238409%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/286%23issuecomment-170238409%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.38%25%60%5Cn%3E%20Merging%20%2A%2A%23286%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60e5d668a%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23286%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Added shields for SonarQube

---

src/main/java/net/masterthought/cucumber/VelocityContextMap.java
src/main/java/net/masterthought/cucumber/charts/JsChartUtil.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/support/StatusCounter.java
src/main/java/net/masterthought/cucumber/json/support/StepObject.java
src/main/java/net/masterthought/cucumber/util/Util.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/287%23issuecomment-170245340%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/287%23issuecomment-170245340%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.36%25%60%5Cn%3E%20Merging%20%2A%2A%23287%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.02%25%2A%2A%20as%20of%20%5B%60388f932%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23287%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Fixed violations reported by SonarQube

---

README.md
src/main/resources/styles/reporting.css

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/288%23issuecomment-170267682%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/288%23issuecomment-170267682%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.36%25%60%5Cn%3E%20Merging%20%2A%2A%23288%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60bb98d5b%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23288%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Linked the project with codacy.com

---

src/main/java/net/masterthought/cucumber/charts/FlashChartBuilder.java
src/main/java/net/masterthought/cucumber/generators/FeatureOverviewPage.java
src/main/java/net/masterthought/cucumber/json/support/Status.java
src/main/resources/templates/pages/featureOverview.vm

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/290%23issuecomment-170287311%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/290%23issuecomment-170287311%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.94%25%60%5Cn%3E%20Merging%20%2A%2A%23290%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.42%25%2A%2A%20as%20of%20%5B%605070ffb%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23290%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Colors might not be displayed in correct order

---

src/main/java/net/masterthought/cucumber/json/support/StatusCounter.java
src/main/java/net/masterthought/cucumber/util/ChartUtil.java
src/main/resources/styles/reporting.css
src/main/resources/templates/pages/tagOverview.vm
src/test/java/net/masterthought/cucumber/ChartUtilTest.java
src/test/java/net/masterthought/cucumber/FeatureTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/293%23issuecomment-170396302%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/293%23issuecomment-170396302%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.69%25%60%5Cn%3E%20Merging%20%2A%2A%23293%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.05%25%2A%2A%20as%20of%20%5B%603ce4c97%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23293%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Fixed minor issues reported by codacy and sonarqube

---

src/main/java/net/masterthought/cucumber/json/Step.java
src/test/java/net/masterthought/cucumber/StepTest.java

Revert escaping output from Step class

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/resources/templates/headers.html
src/main/resources/templates/pages/errorPage.vm
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/296%23issuecomment-170728768%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/296%23issuecomment-170728768%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.92%25%60%5Cn%3E%20Merging%20%2A%2A%23296%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.03%25%2A%2A%20as%20of%20%5B%60b53df00%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23296%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

CSS style file is linked, not included into the HTML page

---

README.md
src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/resources/net/masterthought/cucumber/project1.json

Issue #297
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/298%23issuecomment-171020281%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/298%23issuecomment-171020281%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.34%25%60%5Cn%3E%20Merging%20%2A%2A%23298%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.42%25%2A%2A%20as%20of%20%5B%607f688ee%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23298%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3 …

Tags for feature were not processed (were ignored)

---

src/main/java/net/masterthought/cucumber/ConfigurationOptions.java
src/main/java/net/masterthought/cucumber/json/Hook.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/support/ResultsWithMatch.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/test/resources/net/masterthought/cucumber/project2.json

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/299%23issuecomment-171039639%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/299%23issuecomment-171039639%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.75%25%60%5Cn%3E%20Merging%20%2A%2A%23299%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B1.41%25%2A%2A%20as%20of%20%5B%609dc94b7%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23299%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Removed old, unused methods

---

src/main/java/net/masterthought/cucumber/Configuration.java
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/generators/ErrorPage.java
src/main/java/net/masterthought/cucumber/generators/FeatureOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/FeatureReportPage.java
src/main/java/net/masterthought/cucumber/generators/StepOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagReportPage.java
src/test/java/net/masterthought/cucumber/DocStringTest.java
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/ReportParserTest.java
src/test/java/net/masterthought/cucumber/RowTest.java
src/test/java/net/masterthought/cucumber/ScenarioTest.java
src/test/java/net/masterthought/cucumber/StatusesTest.java
src/test/java/net/masterthought/cucumber/StepTest.java
src/test/java/net/masterthought/cucumber/TagsTest.java

Follow up for pull #300
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/303%23issuecomment-171434800%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/303%23issuecomment-171434800%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.65%25%60%5Cn%3E%20Merging%20%2A%2A%23303%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B1.01%25%2A%2A%20as%20of%20%5B%60be96c56%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23303%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Stores options/configurations/etc in single instance

---

README.md
src/main/java/net/masterthought/cucumber/ReportBuilder.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/304?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/304'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Updated README.md file according to new API

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/generators/ErrorPage.java
src/main/java/net/masterthought/cucumber/generators/FeatureOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/FeatureReportPage.java
src/main/java/net/masterthought/cucumber/generators/StepOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagReportPage.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Embedded.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/support/StatusCounter.java
src/main/java/net/masterthought/cucumber/util/ChartUtil.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/305%23issuecomment-171734841%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/305%23issuecomment-171734841%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.75%25%60%5Cn%3E%20Merging%20%2A%2A%23305%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.01%25%2A%2A%20as%20of%20%5B%60de1cc1a%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23305%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Fix SonarQube and Codacy violations

---

src/main/java/net/masterthought/cucumber/generators/AbstractPage.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/311%23issuecomment-173250587%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/311%23discussion_r50289919%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/311%23issuecomment-173299919%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/311%23discussion_r50305647%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/311%23discussion_r50311084%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/311%23issuecomment-173250587%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22 …

String is no longer supported as a parameter

---

src/main/java/net/masterthought/cucumber/json/Element.java

'type' instead of 'keyword' is validated against 'scenario' keyword
#306
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/312%23issuecomment-173348433%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/312%23issuecomment-173348433%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.72%25%60%5Cn%3E%20Merging%20%2A%2A%23312%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.05%25%2A%2A%20as%20of%20%5B%604575b92%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23312%20%20%20d …

Only English keywords are supported

---

.travis.yml

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/314%23issuecomment-174598951%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/314%23issuecomment-174598951%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.61%25%60%5Cn%3E%20Merging%20%2A%2A%23314%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60fa03720%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23314%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Enable .m2 cache for Travis to speed up building

---

src/main/resources/styles/reporting.css
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/tableHeader.vm

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/319%23issuecomment-181027029%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/319%23issuecomment-181027029%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.61%25%60%5Cn%3E%20Merging%20%2A%2A%23319%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%605e26e4b%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23319%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Removed html tag style (by replacing with class) for header and summary rows in tables

---

src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/generators/FeatureOverviewPage.java
src/main/java/net/masterthought/cucumber/json/support/Status.java
src/main/resources/styles/reporting.css
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/main/resources/templates/tableHeader.vm
src/test/java/net/masterthought/cucumber/json/support/StatusTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/320%23issuecomment-181041836%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/320%23issuecomment-181041836%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.52%25%60%5Cn%3E%20Merging%20%2A%2A%23320%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.09%25%2A%2A%20as%20of%20%5B%60dd7aca6%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23320%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Removed html tag style (by replacing with class) from cells with background

---

src/main/resources/styles/reporting.css
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/321%23issuecomment-181048223%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/321%23issuecomment-181048223%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.52%25%60%5Cn%3E%20Merging%20%2A%2A%23321%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60a21aa5a%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23321%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Removed html tag style (by replacing with class) from cells with duration

---

src/main/java/net/masterthought/cucumber/json/support/StepObject.java
src/main/resources/styles/reporting.css
src/main/resources/templates/pages/stepOverview.vm

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/322%23issuecomment-181051100%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/322%23issuecomment-181051100%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.53%25%60%5Cn%3E%20Merging%20%2A%2A%23322%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.01%25%2A%2A%20as%20of%20%5B%6028fa764%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23322%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Step overview does not present correctly average duration and sum of the items

---

src/main/java/net/masterthought/cucumber/generators/FeatureReportPage.java
src/main/java/net/masterthought/cucumber/generators/TagReportPage.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/support/Status.java
src/main/resources/styles/reporting.css
src/main/resources/templates/footer.vm
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/main/resources/templates/summaryReport.vm
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/json/support/StatusTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/323%23issuecomment-181076903%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/323%23issuecomment-181076903%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.34%25%60%5Cn%3E%20Merging%20%2A%2A%23323%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.19%25%2A%2A%20as%20of%20%5B%6073bb67c%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23323%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Status colors are available only in css/html files

---

src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/support/Status.java
src/main/java/net/masterthought/cucumber/json/support/StepObject.java

Issue #310
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/326%23issuecomment-183628386%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/326%23issuecomment-183628386%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.29%25%60%5Cn%3E%20Merging%20%2A%2A%23326%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.05%25%2A%2A%20as%20of%20%5B%60bfe1d29%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23326%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Failures in before/after hooks are not represented at the Feature Overview

---

src/main/resources/styles/reporting.css
src/main/resources/templates/footer.vm
src/main/resources/templates/pages/errorPage.vm
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/327%23discussion_r52831403%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/327%23discussion_r52831463%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/327%23issuecomment-183717482%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%20d5aa6e6ca8c7b4f59e718ad2f0742fb758d1d23b%20src/main/resources/styles/reporting.css%2030%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/327%23discussion_r52831403%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%21%5BCodacy%5D%28https%3A//www.codacy.com/versioned/images/favicon.png%29%20Issue%20found%3A%20%5BElement%20%28td.duration-for …

Additional CSS improvements

---

src/main/resources/styles/reporting.css
src/main/resources/templates/summaryOverview.vm
src/main/resources/templates/summaryReport.vm

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/331%23issuecomment-183949037%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/331%23issuecomment-183949037%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6091.61%25%60%5Cn%3E%20Merging%20%2A%2A%23331%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%604243cbd%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23331%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

First line of the summary was overlapped by top menu

---

src/main/java/net/masterthought/cucumber/json/DocString.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/main/resources/templates/pages/featureReport.vm
src/test/java/net/masterthought/cucumber/DocStringTest.java
src/test/java/net/masterthought/cucumber/FeatureTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/332%23issuecomment-183992202%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/332%23issuecomment-183992202%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6091.56%25%60%5Cn%3E%20Merging%20%2A%2A%23332%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.05%25%2A%2A%20as%20of%20%5B%6079253df%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23332%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Moved HTML tags out of Java code

---

src/main/resources/templates/summaryOverview.vm

Project name is a required parameter,
so it should be always shown, and not only when is run from jenkins.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/334%23issuecomment-184782948%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/334%23issuecomment-184782948%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6091.57%25%60%5Cn%3E%20Merging%20%2A%2A%23334%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%6059da027%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23334 …

Always show project name

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/generators/ErrorPage.java
src/main/java/net/masterthought/cucumber/generators/FeatureOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/FeatureReportPage.java
src/main/java/net/masterthought/cucumber/generators/StepOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagReportPage.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/337%23issuecomment-185974406%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/337%23issuecomment-185974406%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6091.42%25%60%5Cn%3E%20Merging%20%2A%2A%23337%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.08%25%2A%2A%20as%20of%20%5B%602fff98a%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23337%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Report generates single report

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/resources/css/reporting.css
src/main/resources/templates/headers.html
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/main/resources/templates/summaryOverview.vm
src/main/resources/templates/summaryReport.vm
src/main/resources/templates/tableSorter.vm
src/main/resources/templates/topMenu.vm
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/339%23issuecomment-186868379%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/339%23issuecomment-186868379%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6091.42%25%60%5Cn%3E%20Merging%20%2A%2A%23339%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60fd372b4%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23339%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Layout improvements

---

src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/generators/FeatureOverviewPage.java
src/main/resources/templates/pages/featureOverview.vm
src/test/java/net/masterthought/cucumber/ReportInformationTest.java

Issue #340
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/342%23issuecomment-188504429%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/342%23issuecomment-188504429%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6091.36%25%60%5Cn%3E%20Merging%20%2A%2A%23342%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.07%25%2A%2A%20as%20of%20%5B%600a7f111%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23342%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3 …

Failed features were not counted properly if only background element failed

---

src/main/resources/templates/headers.html
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/343?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/343'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Charts were not displayed on big screens

---

src/main/resources/templates/pages/featureOverview.vm

Now there are: steps, scenarios and features
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/345%23issuecomment-189008923%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/345%23issuecomment-189008923%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6091.06%25%60%5Cn%3E%20Merging%20%2A%2A%23345%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.30%25%2A%2A%20as%20of%20%5B%6077dbd10%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23345%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D …

Added third chart with Features

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/346%23issuecomment-189899494%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/346%23issuecomment-189899494%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6091.06%25%60%5Cn%3E%20Merging%20%2A%2A%23346%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.30%25%2A%2A%20as%20of%20%5B%601159a90%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23346%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

hasBuildPassed could return false even some features were failed

---

src/main/resources/css/reporting.css
src/main/resources/templates/footer.vm
src/main/resources/templates/navigation.vm
src/main/resources/templates/pages/errorPage.vm
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/348?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/348'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Changed footer according to Bootstrap styles/classes

---

src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/resources/templates/footer.vm
src/main/resources/templates/pages/errorPage.vm
src/main/resources/templates/summaryOverview.vm
src/main/resources/templates/summaryReport.vm
src/test/java/net/masterthought/cucumber/ReportInformationTest.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/349?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/349'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Build time was not generated once per report but once per page

---

src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/resources/templates/headers.html
src/main/resources/templates/navigation.vm
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/main/resources/templates/summary.vm
src/main/resources/templates/summaryOverview.vm
src/main/resources/templates/summaryReport.vm
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/350?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/350'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Added one generic summary section for all pages

---

src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/resources/templates/footer.vm
src/main/resources/templates/navigation.vm
src/main/resources/templates/summary.vm

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/351%23issuecomment-190855321%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/351%23issuecomment-190855321%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6091.09%25%60%5Cn%3E%20Merging%20%2A%2A%23351%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.41%25%2A%2A%20as%20of%20%5B%604989625%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23351%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Fixed summary - NPE when build number was not provided

---

src/main/resources/css/reporting.css
src/main/resources/templates/pages/featureOverview.vm

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/353?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/353'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Feature charts are displayed within carousel

---

src/main/resources/templates/headers.vm
src/main/resources/templates/macros/title.vm
src/main/resources/templates/pages/errorPage.vm
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/main/resources/templates/summary.vm

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/354?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/354'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Page title is generated by macros

---

src/main/resources/templates/headers.vm
src/main/resources/templates/macros/navigation.vm
src/main/resources/templates/pages/errorPage.vm
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/357?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/357'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Migrated navigation.vm to macro includeNavigation

---

src/main/resources/css/reporting.css
src/main/resources/templates/macros/tableHeader.vm
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/358?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/358'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Put all tables into container class

---

pom.xml
src/main/java/net/masterthought/cucumber/ReportBuilder.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/359?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/359'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Preparing for new release and new test approach

---

.travis.yml
appveyor.yml
pom.xml
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/ValidationException.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/generators/ErrorPage.java
src/main/java/net/masterthought/cucumber/generators/FeatureOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/FeatureReportPage.java
src/main/java/net/masterthought/cucumber/generators/StepOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagReportPage.java
src/main/resources/templates/footer.html
src/main/resources/templates/macros/navigation.vm
src/test/java/net/masterthought/cucumber/ReportGenerator.java
src/test/java/net/masterthought/cucumber/templates/CommonTemplateIntegrationTest.java
src/test/java/net/masterthought/cucumber/templates/ElementWrapper.java
src/test/java/net/masterthought/cucumber/templates/TemplateUtility.java

navigation
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/360%23issuecomment-192468878%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/360%23issuecomment-192468878%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.62%25%60%5Cn%3E%20Merging%20%2A%2A%23360%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.44%25%2A%2A%20as%20of%20%5B%60b5312b8%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23360%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

New test approach for web pages

---

src/test/java/net/masterthought/cucumber/ReportGenerator.java
src/test/java/net/masterthought/cucumber/templates/CommonTemplateIntegrationTest.java
src/test/resources/jsons-samples/sample.json

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/361%23issuecomment-192502450%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/361%23issuecomment-192502450%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.62%25%60%5Cn%3E%20Merging%20%2A%2A%23361%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.31%25%2A%2A%20as%20of%20%5B%600fb8466%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23361%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Introduced new JSON directory for specified JSON files

---

src/main/resources/css/reporting.css
src/main/resources/templates/headers.vm
src/main/resources/templates/macros/header.vm
src/main/resources/templates/pages/errorPage.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/test/java/net/masterthought/cucumber/generators/FeatureOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/PageIntegrationTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/365%23issuecomment-195527877%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/365%23issuecomment-195527877%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.93%25%60%5Cn%3E%20Merging%20%2A%2A%23365%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60ffd138a%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23365%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Fixed: date in reports were aligned to the left

---

src/main/resources/templates/macros/header.vm
src/main/resources/templates/macros/title.vm
src/main/resources/templates/pages/errorPage.vm
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/366%23issuecomment-195700184%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/366%23issuecomment-195700184%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.93%25%60%5Cn%3E%20Merging%20%2A%2A%23366%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60e699cec%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23366%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Added left and right margins for all containers

---

src/main/java/net/masterthought/cucumber/generators/FeatureReportPage.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/resources/css/reporting.css
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/tagReport.vm

Issue #364
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/368%23issuecomment-195822126%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/368%23issuecomment-195822126%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.93%25%60%5Cn%3E%20Merging%20%2A%2A%23368%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%6054d9f29%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23368%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Show scenario descriptions in reports

---

src/main/resources/templates/headers.vm
src/main/resources/templates/macros/header.vm
src/main/resources/templates/macros/navigation.vm
src/main/resources/templates/macros/scenarios.vm
src/main/resources/templates/macros/tableHeader.vm
src/main/resources/templates/macros/title.vm
src/main/resources/templates/pages/errorPage.vm
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepOverview.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/369%23issuecomment-195835282%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/369%23issuecomment-195835282%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.93%25%60%5Cn%3E%20Merging%20%2A%2A%23369%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60c3d1850%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23369%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Scenarios in feature and tag report are printed with same macro

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/generators/FeaturesOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/StepsOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagsOverviewPage.java
src/main/resources/templates/headers.vm
src/main/resources/templates/macros/lead.vm
src/main/resources/templates/macros/navigation.vm
src/main/resources/templates/macros/title.vm
src/main/resources/templates/pages/errorPage.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/featuresOverview.vm
src/main/resources/templates/pages/stepsOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/main/resources/templates/pages/tagsOverview.vm
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/generators/FeatureOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/Page.java
src/test/java/net/masterthought/cucumber/generators/PageIntegrationTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/370%23issuecomment-195952144%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/370%23issuecomment-195952144%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.93%25%60%5Cn%3E%20Merging%20%2A%2A%23370%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60f7c2f7b%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23370%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Build title is added to the page title

---

src/main/resources/templates/pages/featuresOverview.vm
src/main/resources/templates/pages/tagsOverview.vm
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageIntegrationTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/372%23issuecomment-197554608%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/372%23issuecomment-197554608%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.93%25%60%5Cn%3E%20Merging%20%2A%2A%23372%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60d55a97e%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23372%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Added TagsOverviewPageIntegrationTest.java

---

src/main/resources/css/reporting.css
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/featuresOverview.vm
src/main/resources/templates/pages/stepsOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/main/resources/templates/pages/tagsOverview.vm
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageIntegrationTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/373%23issuecomment-198033860%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/373%23issuecomment-198033860%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.93%25%60%5Cn%3E%20Merging%20%2A%2A%23373%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%603c8099e%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23373%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Added StepsOverviewPageIntegrationTest to exam stepsOverview.vm template

---

src/main/java/net/masterthought/cucumber/json/Step.java
src/main/resources/css/reporting.css
src/main/resources/templates/pages/featuresOverview.vm
src/main/resources/templates/pages/tagsOverview.vm
src/test/java/net/masterthought/cucumber/StepTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/374%23issuecomment-198049124%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/374%23issuecomment-198049124%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.93%25%60%5Cn%3E%20Merging%20%2A%2A%23374%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%606db13dc%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23374%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Unified colors in table and report, added more brightness

---

src/main/java/net/masterthought/cucumber/json/support/StatusCounter.java
src/main/java/net/masterthought/cucumber/json/support/StepObject.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/main/resources/templates/pages/stepsOverview.vm

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/375%23issuecomment-198103997%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/375%23issuecomment-198103997%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6091.02%25%60%5Cn%3E%20Merging%20%2A%2A%23375%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.09%25%2A%2A%20as%20of%20%5B%605e8c389%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23375%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

StatsOverview report shows real step status not only passed or failed

---

src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageIntegrationTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/377%23issuecomment-198573473%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/377%23issuecomment-198573473%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.72%25%60%5Cn%3E%20Merging%20%2A%2A%23377%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.30%25%2A%2A%20as%20of%20%5B%60d14ec7b%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23377%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Added StepsOverviewPageIntegrationTest.java

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/generators/StepsOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagsOverviewPage.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/main/resources/templates/headers.vm
src/main/resources/templates/macros/navigation.vm
src/main/resources/templates/macros/scenarios.vm
src/main/resources/templates/macros/tags.vm
src/main/resources/templates/pages/featureReport.vm
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/ScenarioTest.java
src/test/java/net/masterthought/cucumber/generators/PageIntegrationTest.java

Reverted report file names to keep backwards compatibility
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/379%23issuecomment-198939942%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/379%23issuecomment-198939942%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.98%25%60%5Cn%3E%20Merging%20%2A%2A%23379%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.08%25%2A%2A%20as%20of%20%5B%60d4bae45%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23379%20%20%20diff%20%40%40%5 …

Tags are included by macro

---

pom.xml

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/381%23issuecomment-200499221%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/381%23issuecomment-200499221%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.98%25%60%5Cn%3E%20Merging%20%2A%2A%23381%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%6036ad0e1%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23381%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Releasing version 2.1.0

---

pom.xml
src/main/resources/css/reporting.css

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/384%23issuecomment-203327094%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/384%23discussion_r57970069%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/384%23issuecomment-203327094%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.98%25%60%5Cn%3E%20Merging%20%2A%2A%23384%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60a84cbaa%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23384%20%20% …

updated css file with report colours

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/resources/templates/macros/navigation.vm
src/main/resources/templates/pages/errorPage.vm
src/test/java/net/masterthought/cucumber/generators/PageIntegrationTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/385%23issuecomment-204138179%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/385%23issuecomment-204138179%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.98%25%60%5Cn%3E%20Merging%20%2A%2A%23385%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60ec880d0%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23385%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

When report fails, static files were not copied

---

src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/generators/StepsOverviewPage.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/support/Reportable.java
src/main/java/net/masterthought/cucumber/json/support/StepObject.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/main/java/net/masterthought/cucumber/util/ChartUtil.java
src/main/resources/templates/headers.vm
src/main/resources/templates/macros/reportHeader.vm
src/main/resources/templates/macros/reportTable.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/featuresOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/main/resources/templates/pages/tagsOverview.vm
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/StatusesTest.java
src/test/java/net/masterthought/cucumber/TagsTest.java
src/test/java/net/masterthought/cucumber/generators/ElementWrapper.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/386%23issuecomment-204570720%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/386%23issuecomment-204570720%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.86%25%60%5Cn%3E%20Merging%20%2A%2A%23386%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.12%25%2A%2A%20as%20of%20%5B%60082c098%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23386%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Report table is more generic

---

src/main/resources/templates/macros/title.vm
src/test/java/net/masterthought/cucumber/generators/ErrorPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/Page.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageIntegrationTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/387%23issuecomment-204808203%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/387%23issuecomment-204808203%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.86%25%60%5Cn%3E%20Merging%20%2A%2A%23387%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60751be25%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23387%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Added tests to validate <title>

---

src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/generators/FeaturesOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagsOverviewPage.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/main/java/net/masterthought/cucumber/reports/OverviewReport.java
src/main/java/net/masterthought/cucumber/reports/Reportable.java
src/main/resources/templates/headers.vm
src/main/resources/templates/macros/statsTable.vm
src/main/resources/templates/pages/featuresOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/main/resources/templates/pages/tagsOverview.vm
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/TagsTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/388%23issuecomment-204818782%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/388%23issuecomment-204818782%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.22%25%60%5Cn%3E%20Merging%20%2A%2A%23388%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.64%25%2A%2A%20as%20of%20%5B%60d57062e%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23388%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Moved duplicated HTML codes into Velocity macros

---

src/main/java/net/masterthought/cucumber/generators/FeatureReportPage.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/Tag.java
src/main/resources/css/reporting.css
src/main/resources/templates/headers.vm
src/main/resources/templates/macros/keyword.vm
src/main/resources/templates/macros/scenarios.vm
src/main/resources/templates/macros/tags.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/featuresOverview.vm
src/main/resources/templates/pages/stepsOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/main/resources/templates/pages/tagsOverview.vm
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/StepTest.java
src/test/java/net/masterthought/cucumber/generators/ElementWrapper.java
src/test/java/net/masterthought/cucumber/generators/ErrorPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/Page.java
src/test/java/net/masterthought/cucumber/generators/PageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/ReportPage.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageIntegrationTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/389%23issuecomment-204989461%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/389%23issuecomment-204989461%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.83%25%60%5Cn%3E%20Merging%20%2A%2A%23389%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.39%25%2A%2A%20as%20of%20%5B%608222fba%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23389%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Added FeaturesReportPageIntegrationTest

---

src/main/java/net/masterthought/cucumber/util/Util.java
src/main/resources/css/reporting.css
src/main/resources/templates/pages/tagReport.vm
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/StepTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/Page.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageIntegrationTest.java
src/test/resources/json/sample.json

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/391%23issuecomment-205522630%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/391%23issuecomment-205522630%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.56%25%60%5Cn%3E%20Merging%20%2A%2A%23391%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.73%25%2A%2A%20as%20of%20%5B%60908e070%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23391%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

UI improvements

---

src/main/java/net/masterthought/cucumber/json/Embedded.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/main/resources/templates/macros/scenarios.vm
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/StepTest.java
src/test/java/net/masterthought/cucumber/generators/Page.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageIntegrationTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/392%23issuecomment-206545451%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/392%23issuecomment-206545451%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.68%25%60%5Cn%3E%20Merging%20%2A%2A%23392%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.12%25%2A%2A%20as%20of%20%5B%60644d725%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23392%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Code cleanup

---

src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/resources/css/reporting.css
src/main/resources/templates/macros/scenarios.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/stepsOverview.vm
src/test/java/net/masterthought/cucumber/StepTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageIntegrationTest.java
src/test/resources/json/sample.json

- added hooks to sample json file
- added more durations so there is mostly 000 ms presented
- some css improvements
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/395%23issuecomment-207983032%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/395%23issuecomment-207983032%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6090.83%25%60%5Cn%3E%20Merging%20%2A%2A%23395%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.15%25%2A%2A%20as%20of%20%5B%6068c46e4%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20 …

@Before and !After cleanup

---

src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Result.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/main/java/net/masterthought/cucumber/reports/OverviewReport.java
src/main/java/net/masterthought/cucumber/reports/Reportable.java
src/main/java/net/masterthought/cucumber/util/ChartUtil.java
src/main/resources/templates/headers.vm
src/main/resources/templates/macros/hooks.vm
src/main/resources/templates/macros/keyword.vm
src/main/resources/templates/macros/reportTable.vm
src/main/resources/templates/macros/scenarios.vm
src/main/resources/templates/macros/statsTable.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/tagReport.vm
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/StepTest.java
src/test/java/net/masterthought/cucumber/TagsTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/Page.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/397%23issuecomment-208088141%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/397%23issuecomment-208088141%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.51%25%60%5Cn%3E%20Merging%20%2A%2A%23397%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.94%25%2A%2A%20as%20of%20%5B%6028b32af%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23397%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Moved HTML code form Java to velocity templates

---

src/main/java/net/masterthought/cucumber/json/Step.java
src/main/resources/css/reporting.css
src/main/resources/templates/macros/scenarios.vm
src/test/java/net/masterthought/cucumber/DocStringTest.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/generators/ElementWrapper.java

Removed unused CSS styles
Added debug message to ElementWrapper class
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/398%23issuecomment-208517731%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/398%23issuecomment-208517731%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.59%25%60%5Cn%3E%20Merging%20%2A%2A%23398%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20increase%20coverage%20by%20%2A%2A%2B0.08%25%2A%2A%20as%20of%20%5B%60c574405%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23398%20%20%20di …

doc_string is displayed as it is (without converting to html code)

---

src/main/resources/templates/macros/page/lead.vm
src/main/resources/templates/macros/report/elements.vm
src/main/resources/templates/macros/report/hooks.vm
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/generators/ElementWrapper.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/Page.java
src/test/java/net/masterthought/cucumber/generators/PageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageIntegrationTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/402%23issuecomment-210788580%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/402%23issuecomment-210788580%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6089.56%25%60%5Cn%3E%20Merging%20%2A%2A%23402%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60572c4c6%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23402%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Further CSS cleanup and encapsulation

---

README.md
pom.xml

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/406?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/406'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Preparing for next development iteration

---

src/main/java/net/masterthought/cucumber/ReportParser.java

replace `contan` by `contain` in `"File '%s' does not contan features!"`
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/409%23issuecomment-211358309%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/409%23issuecomment-211358309%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6060.41%25%60%5Cn%3E%20Merging%20%2A%2A%23409%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%60cb728f2%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23409%20%20%20diff%20%40%40%5Cn%3D%3D%3 …

fix small typo on exception message

---

src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/support/StatusCounter.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/main/resources/css/reporting.css
src/main/resources/templates/macros/report/brief.vm
src/main/resources/templates/macros/report/elements.vm
src/main/resources/templates/macros/report/hooks.vm
src/test/java/net/masterthought/cucumber/ScenarioTest.java
src/test/java/net/masterthought/cucumber/generators/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/helpers/ElementAssertion.java
src/test/java/net/masterthought/cucumber/generators/helpers/StepAssertion.java
src/test/java/net/masterthought/cucumber/generators/helpers/WebAssertion.java

Issue #282
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/415?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/415'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Makes hooks and steps expandable

---

src/main/java/net/masterthought/cucumber/json/Embedded.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageIntegrationTest.java
src/test/resources/json/sample.json

Issue #412
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/417?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/417'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Added support for JSON embedded type

---

src/main/java/net/masterthought/cucumber/json/Element.java
src/main/resources/templates/macros/report/elements.vm
src/main/resources/templates/macros/report/hooks.vm
src/test/java/net/masterthought/cucumber/generators/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/TagReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/helpers/ElementAssertion.java
src/test/java/net/masterthought/cucumber/generators/helpers/HooksAssertion.java
src/test/java/net/masterthought/cucumber/generators/helpers/StepsAssertion.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/418?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/418'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Added integrations tests for expandable hooks and steps

---

README.md
src/main/java/net/masterthought/cucumber/util/ChartUtil.java
src/test/java/net/masterthought/cucumber/ChartUtilTest.java
src/test/java/net/masterthought/cucumber/json/EmbeddingTest.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/421?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/421'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Added tests for Embedding class + new codecov coverage diagram

---

README.md
src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/resources/css/reporting.css

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/431%23issuecomment-216122609%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/431%23issuecomment-216122609%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5Bcc-pull%5D%20is%20%2A%2A69.51%25%2A%2A%5Cn%3E%20Merging%20%5B%23431%5D%5Bcc-pull%5D%20into%20%5Bmaster%5D%5Bcc-base-branch%5D%20will%20increase%20coverage%20by%20%2A%2A%2B%3C.01%25%2A%2A%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%20%20%20%23431%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3 …

Hooks did not have left box-shadow on hover

---

src/main/resources/templates/head.html

This is an issue when multiple entries in a list have the same value.
If step A and step B both took 3ms, then a stable sort will guarantee
that every time the list is sorted, A and B will appear in the same
order with respect to another. Some sorting implementations can't make
this guarantee.
By default, tablesorter disables this.
More info: https://en.wikipedia.org/wiki/Sorting_algorithm#Stability
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/425%23issuecomment-216073429%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/425%23issuecomment-216119986%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cuc …

Use stable sorting on tables

---

src/main/resources/css/reporting.css

Having the bars persistent makes it easier to visually group long lists
of steps.
Used a lighter color to match theme while retaining enough visual
contrast to be noticeable.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/434%23discussion_r61848427%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/434%23issuecomment-216464496%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/434%23issuecomment-216465820%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/434%23issuecomment-216474205%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/434%2 …

Make box-shadows persistent, lighter

---

src/main/resources/templates/macros/report/embeddings.vm

Fix for issue https://github.com/damianszczepanik/cucumber-reporting/issues/380
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/444?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/444'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Added image/url type to embed image link to report instead of image data

---

src/main/java/net/masterthought/cucumber/generators/FeatureReportPage.java
src/main/java/net/masterthought/cucumber/generators/StepsOverviewPage.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/ErrorPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeatureReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageTest.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/445?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/445'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Added tests for generators

---

README.md

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/448?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/448'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Shield for Appveyor displayed build status for last build not master

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportParser.java
src/test/java/net/masterthought/cucumber/ReportGenerator.java
src/test/java/net/masterthought/cucumber/ReportParserTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/ErrorPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/PageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagsOverviewPageIntegrationTest.java
src/test/resources/json/invalid-report.json
src/test/resources/json/invalid.json
src/test/resources/json/simple.json

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/449?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/449'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Improved support for invalid of empty JSON reports

---

src/main/resources/templates/macros/report/statsTable.vm
src/test/java/net/masterthought/cucumber/generators/integrations/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagsOverviewPageIntegrationTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/447%23issuecomment-221925582%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/447%23issuecomment-222165472%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/447%23issuecomment-222166412%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/447%23issuecomment-222202744%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/447%23issuecomment-221925582%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%27m%20OK%20about%20this%20change.%20Fix%20tests%20and%20prepare%20update.%22%2C%20%22created_a …

it would be more interesting to highlight the failed scenarios

---

pom.xml
src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/ValidationException.java
src/main/java/net/masterthought/cucumber/json/support/StatusCounter.java
src/main/java/net/masterthought/cucumber/json/support/StepObject.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/main/resources/templates/generators/stepsOverview.vm
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/json/ResultTest.java
src/test/java/net/masterthought/cucumber/json/support/StepObjectTest.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/452?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/452'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Unit tests for StepObject class

---

src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/main/resources/css/reporting.css
src/test/java/net/masterthought/cucumber/ChartUtilTest.java
src/test/java/net/masterthought/cucumber/DocStringTest.java
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/ScenarioTest.java
src/test/java/net/masterthought/cucumber/StepTest.java
src/test/java/net/masterthought/cucumber/TagsTest.java
src/test/java/net/masterthought/cucumber/json/support/StatusTest.java
src/test/java/net/masterthought/cucumber/json/support/TagObjectTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/453%23discussion_r65000085%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/453%23issuecomment-222351454%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/453%23issuecomment-222351454%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5Bcc-pull%5D%20is%20%2A%2A87.61%25%2A%2A%5Cn%3E%20Merging%20%5B%23453%5D%5Bcc-pull%5D%20into%20%5Bmaster%5D%5Bcc-base-branch%5D%20will%20increase%20coverage%20by%20%2A%2A%3C.01%25%2A%2A%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20%20master%20 …

Unit tests for TagObject class

---

src/test/java/net/masterthought/cucumber/ReportGenerator.java
src/test/java/net/masterthought/cucumber/ReportParserTest.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/ErrorPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeatureReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/ErrorPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/PageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/json/EmbeddingTest.java
src/test/java/net/masterthought/cucumber/json/ResultTest.java
src/test/java/net/masterthought/cucumber/json/RowTest.java
src/test/java/net/masterthought/cucumber/json/TagTest.java

typo fix and adding locale to a test to not depend on default locale (tests currently fail with FR locale).
Sorry about PR #455, I had also done some changes (for another PR) and committed too fast
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/456%23issuecomment-222972172%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/456%23issuecomment-223066389%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/456%23issuecomment-223205450%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/456%23issuecomment-222972172%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22 …

Test enhancement

---

pom.xml
src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Embedding.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Output.java
src/main/java/net/masterthought/cucumber/json/Result.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/deserializers/OutputDeserializer.java
src/main/resources/css/reporting.css
src/main/resources/templates/headers.vm
src/main/resources/templates/macros/report/elements.vm
src/main/resources/templates/macros/report/outputs.vm
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/ElementAssertion.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/OutputAssertion.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/StepAssertion.java
src/test/resources/json/sample.json

Issue jenkinsci/cucumber-reports-plugin/issues/29
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/459?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/459'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Migrated from gson to jackson library

---

src/main/java/net/masterthought/cucumber/Configuration.java
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/json/DocString.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Embedding.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Row.java
src/main/java/net/masterthought/cucumber/json/deserializers/CucumberJsonDeserializer.java
src/main/java/net/masterthought/cucumber/json/deserializers/EmbeddingDeserializer.java
src/main/java/net/masterthought/cucumber/json/deserializers/OutputDeserializer.java
src/main/resources/templates/macros/report/embeddings.vm
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/ReportGenerator.java
src/test/java/net/masterthought/cucumber/ScenarioTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/EmbeddingAssertion.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/460%23issuecomment-223778266%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/460%23issuecomment-223778266%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5Bcc-pull%5D%20is%20%2A%2A88.40%25%2A%2A%5Cn%3E%20Merging%20%5B%23460%5D%5Bcc-pull%5D%20into%20%5Bmaster%5D%5Bcc-base-branch%5D%20will%20increase%20coverage%20by%20%2A%2A1.02%25%2A%2A%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%20%20%20%23460%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Embeddings are stored into the files by deserializers not ReportBuilder

---

src/main/java/net/masterthought/cucumber/json/Embedding.java
src/main/java/net/masterthought/cucumber/json/Hook.java
src/main/resources/templates/headers.vm
src/main/resources/templates/macros/report/elements.vm
src/main/resources/templates/macros/report/hooks.vm
src/main/resources/templates/macros/report/steps.vm
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/HookAssertion.java
src/test/java/net/masterthought/cucumber/json/EmbeddingTest.java
src/test/resources/json/sample.json

Issue #439
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/462?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/462'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Embedded images are displayed for hooks #Before and @After

---

pom.xml

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/466?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/466'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Releasing version 2.4.0

---

src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/json/Hook.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/support/Resultsable.java
src/test/java/net/masterthought/cucumber/ConfigurationTest.java
src/test/java/net/masterthought/cucumber/ReportParserTest.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeatureReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/json/EmbeddingTest.java
src/test/java/net/masterthought/cucumber/json/OutputTest.java
src/test/java/net/masterthought/cucumber/json/ResultTest.java
src/test/java/net/masterthought/cucumber/json/RowTest.java
src/test/java/net/masterthought/cucumber/json/TagTest.java
src/test/java/net/masterthought/cucumber/json/support/StatusTest.java
src/test/java/net/masterthought/cucumber/json/support/StepObjectTest.java
src/test/java/net/masterthought/cucumber/json/support/TagObjectTest.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/468?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/468'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Added units tests for TagObject class

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/resources/templates/macros/report/embeddings.vm
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/EmbeddingAssertion.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/469?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/469'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Report was not generated for the first time (in clear workspace)

---

src/test/java/net/masterthought/cucumber/generators/integrations/PageTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/478%23issuecomment-226979209%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/478%23issuecomment-226979209%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5Bcc-pull%5D%20is%20%2A%2A85.93%25%2A%2A%5Cn%3E%20Merging%20%5B%23478%5D%5Bcc-pull%5D%20into%20%5Bmaster%5D%5Bcc-base-branch%5D%20will%20not%20change%20coverage%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%20%20%20%23478%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Fix IntelliJ compile warning: Charsets deprecated

---

src/main/resources/templates/macros/report/element.vm

Ran tests and generated a sample report, didn't see any issues.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/475%23issuecomment-226975162%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/475%23issuecomment-226975162%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5Bcc-pull%5D%20is%20%2A%2A85.93%25%2A%2A%5Cn%3E%20Merging%20%5B%23475%5D%5Bcc-pull%5D%20into%20%5Bmaster%5D%5Bcc-base-branch%5D%20will%20not%20change%20coverage%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%20%20%20%23475%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3 …

Fix typo in element.vm

---

src/main/java/net/masterthought/cucumber/json/deserializers/EmbeddingDeserializer.java

This is a continuation of my comment [here](https://github.com/jenkinsci/cucumber-reports-plugin/issues/29#issuecomment-230088490).  The embedding file _is_ being created, it's just served with a strange encoding and my browser reports it as an svg/xml icon:
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/489%23issuecomment-230094488%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/489%23issuecomment-230094681%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/489%23issuecomment-230094488%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Here%20it%20is%20saved%20to%20my%20comput …

Fixing embedding deserialization charset.

---

src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/ValidationException.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Embedding.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/deserializers/CucumberJsonDeserializer.java
src/main/java/net/masterthought/cucumber/json/deserializers/EmbeddingDeserializer.java
src/main/java/net/masterthought/cucumber/json/deserializers/OutputDeserializer.java
src/test/java/net/masterthought/cucumber/FileReaderUtil.java
src/test/java/net/masterthought/cucumber/TagTest.java
src/test/java/net/masterthought/cucumber/json/support/TagObjectTest.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/490?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/490'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Equal and sorting improvements

---

src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/resources/templates/macros/report/reportHeader.vm
src/main/resources/templates/macros/report/reportTable.vm
src/main/resources/templates/macros/report/statsTable.vm
src/test/java/net/masterthought/cucumber/json/FeatureTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/495%23issuecomment-233181439%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/495%23issuecomment-233181439%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5Bcc-pull%5D%20is%20%2A%2A90.35%25%2A%2A%5Cn%3E%20Merging%20%5B%23495%5D%5Bcc-pull%5D%20into%20%5Bmaster%5D%5Bcc-base-branch%5D%20will%20increase%20coverage%20by%20%2A%2A0.17%25%2A%2A%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%20%20%20%23495%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Parallel tests were not displayed in summary table

---

pom.xml
src/main/java/net/masterthought/cucumber/Configuration.java
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/resources/templates/macros/page/navigation.vm
src/test/java/net/masterthought/cucumber/ConfigurationTest.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/PageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/NavigationItemAssertion.java

Issue https://github.com/jenkinsci/cucumber-reports-plugin/issues/62
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/501%23issuecomment-234734896%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/501%23issuecomment-234734896%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5Bcc-pull%5D%20is%2090.90%25%20%28diff%3A%20100%25%29%5Cn%3E%20Merging%20%5B%23501%5D%5Bcc-pull%5D%20into%20%5Bmaster%5D%5Bcc-base-branch%5D%20will%20decrease%20coverage%20by%20%2A%2A0.08%25%2A%2A%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%20%20%20%2 …

Support for Folder plugin

---

src/main/resources/css/reporting.css
src/main/resources/templates/generators/featuresOverview.vm

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/506%23issuecomment-236015436%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/506%23issuecomment-236015436%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20wonder%20why%20not%20all%20builds%20have%20started...%22%2C%20%22created_at%22%3A%20%222016-07-28T20%3A29%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9612911%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a …

Use FA chevrons for clearer carousel arrows

---

pom.xml
src/main/java/net/masterthought/cucumber/Configuration.java
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/generators/FailuresOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/FeaturesOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/StepsOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagsOverviewPage.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportGenerator.java
src/test/java/net/masterthought/cucumber/ReportParserTest.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/509?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/509'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Added tests for ReportBuilder

---

pom.xml
src/main/resources/css/reporting.css
src/main/resources/templates/macros/page/title.vm
src/main/resources/templates/macros/report/reportHeader.vm
src/main/resources/templates/macros/report/reportTable.vm
src/main/resources/templates/macros/report/statsTable.vm
src/test/java/net/masterthought/cucumber/generators/integrations/ErrorPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FailuresOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagsOverviewPageIntegrationTest.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/511?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/511'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Displays 'Total' column at the last position, added colors

---

pom.xml
src/main/java/net/masterthought/cucumber/json/Result.java
src/main/java/net/masterthought/cucumber/json/deserializers/CucumberJsonDeserializer.java
src/main/java/net/masterthought/cucumber/json/deserializers/EmbeddingDeserializer.java
src/main/java/net/masterthought/cucumber/json/deserializers/OutputDeserializer.java
src/main/java/net/masterthought/cucumber/json/deserializers/StatusDeserializer.java
src/main/java/net/masterthought/cucumber/json/support/Status.java
src/test/java/net/masterthought/cucumber/json/deserializers/StatusDeserializerTest.java
src/test/resources/json/sample.json

Issue #467
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/513%23discussion_r76350311%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%206929d49e0d09b45a9b71067d521a3ce4b5549fee%20src/test/java/net/masterthought/cucumber/json/deserializers/StatusDeserializerTest.java%2063%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/513%23discussion_r76350311%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%21%5BCodacy%5D%28https%3A//www.codacy.com/assets/images/favicon.png%29%20Issue%20found%3A%20%5BJUnit%20tests%20should%20include%20assert%28%29%20or%20fail%28%29%5D%28https%3A//www.codacy.com/app/damianszczepanik/cucumber-reporting/file/3579498689/issues/source%3Fbid%3D …

Support for AMBIGUOUS status

---

pom.xml
src/main/java/net/masterthought/cucumber/Configuration.java
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/support/StatusCounter.java
src/test/java/net/masterthought/cucumber/ConfigurationTest.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportResultTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/json/ElementTest.java
src/test/java/net/masterthought/cucumber/json/FeatureTest.java
src/test/java/net/masterthought/cucumber/json/support/TagObjectTest.java
src/test/resources/json/sample.json

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/519?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/519'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Removed flags from configuration

---

src/main/resources/templates/macros/report/reportHeader.vm
src/main/resources/templates/macros/report/reportTable.vm
src/main/resources/templates/macros/report/statsTable.vm
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagsOverviewPageIntegrationTest.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/520?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/520'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Changed order of displayed sections to: steps -> scenarios -> features

---

src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/Reportable.java
src/main/java/net/masterthought/cucumber/generators/FeaturesOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/OverviewReport.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/support/Status.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/main/resources/templates/js/features-chart.js
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/OverviewReportTest.java
src/test/java/net/masterthought/cucumber/json/FeatureTest.java
src/test/java/net/masterthought/cucumber/json/support/TagObjectTest.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/521?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/521'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Extended Reportable interface (by features)

---

appveyor.yml

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/526%23issuecomment-248944111%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/526%23issuecomment-248944111%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%28https%3A//codecov.io/gh/damianszczepanik/cucumber-reporting/pull/526%3Fsrc%3Dpr%29%20is%2097.00%25%20%28diff%3A%20100%25%29%5Cn%3E%20Merging%20%5B%23526%5D%28https%3A//codecov.io/gh/damianszczepanik/cucumber-reporting/pull/526%3Fsrc%3Dpr%29%20into%20%5Bmaster%5D%28https%3A//codecov.io/gh/damianszczepanik/cucumber-reporting/branch/master%3Fsrc%3Dpr%29%20will%20not% …

Fixed M2_HOME for Appveyor CI

---

src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/resources/templates/generators/overviewFeatures.vm
src/main/resources/templates/generators/overviewSteps.vm
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportGenerator.java
src/test/java/net/masterthought/cucumber/ReportParserTest.java
src/test/java/net/masterthought/cucumber/generators/OverviewReportTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FailuresOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/PageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/json/OutputTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/527%23discussion_r80149174%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/527%23discussion_r80149172%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%20b6a16e94e3e63d70ddb0d6bbef492081f115cdc7%20src/test/java/net/masterthought/cucumber/ReportBuilderTest.java%20117%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/527%23discussion_r80149172%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%21%5BCodacy%5D%28https%3A//www.codacy.com/assets/images/favicon.png%29%20Issue%20found%3A%20%5BAvoid%20unused%20local%20variables%20such%20as%20%27errorMessage%27.%5D%28https%3A//www.codacy.com/app/damia …

Report validation is more restrictive

---

src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Tag.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/main/resources/templates/macros/report/element.vm
src/main/resources/templates/macros/report/steps.vm
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportResultTest.java
src/test/java/net/masterthought/cucumber/generators/FailuresOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/json/ElementTest.java
src/test/java/net/masterthought/cucumber/json/FeatureTest.java
src/test/java/net/masterthought/cucumber/json/TagTest.java
src/test/java/net/masterthought/cucumber/json/support/TagObjectTest.java

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/528?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/528'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Improved code that counts tags

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/Trends.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/generators/FailuresOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/FeaturesOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/StepsOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TagsOverviewPage.java
src/main/java/net/masterthought/cucumber/generators/TrendsOverviewPage.java
src/main/resources/templates/js/trends-chart.js
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportGenerator.java
src/test/java/net/masterthought/cucumber/TrendsTest.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/ErrorPageTest.java
src/test/java/net/masterthought/cucumber/generators/FailuresOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeatureReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TrendsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/PageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TrendsOverviewPageIntegrationTest.java
src/test/resources/cucumber-trends.json

Trends - reading and updating model

---

src/main/java/net/masterthought/cucumber/json/Result.java
src/test/java/net/masterthought/cucumber/json/ResultTest.java
src/test/java/net/masterthought/cucumber/json/StepTest.java

Issue damianszczepanik/cucumber-sandwich/issues/29

Error message was not escaped

---

src/main/resources/templates/macros/page/navigation.vm
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/NavigationItemAssertion.java

Previously referred to last build that may not be completed so the report could not be ready

"Last result" refers to last completed build

---

src/main/resources/css/cucumber.css
src/main/resources/templates/generators/overviewFailures.vm
src/main/resources/templates/generators/overviewFeatures.vm
src/main/resources/templates/generators/overviewSteps.vm
src/main/resources/templates/generators/overviewTags.vm
src/main/resources/templates/generators/reportFeature.vm
src/main/resources/templates/generators/reportTag.vm
src/main/resources/templates/headers.vm
src/main/resources/templates/macros/page/expandAllButtons.vm
src/main/resources/templates/macros/report/reportTable.vm
src/test/java/net/masterthought/cucumber/generators/integrations/FailuresOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/DocumentAssertion.java

Added buttons for expand all and collapse all

---

src/main/java/net/masterthought/cucumber/json/Embedding.java
src/main/resources/templates/macros/report/embeddings.vm
src/test/java/net/masterthought/cucumber/json/EmbeddingTest.java
src/test/resources/json/sample.json

Issue https://github.com/jenkinsci/cucumber-reports-plugin/issues/92

Support for XML files (embeddings)

---

.travis.yml

Reverts damianszczepanik/cucumber-reporting#549

Revert "Fixed coverity report"

---

README.md
src/main/java/net/masterthought/cucumber/Configuration.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/resources/templates/macros/page/navigation.vm
src/test/java/net/masterthought/cucumber/ConfigurationTest.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/ErrorPageTest.java
src/test/java/net/masterthought/cucumber/generators/FailuresOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeatureReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TrendsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/NavigationItemAssertion.java

Issue jenkinsci/cucumber-reports-plugin/issues/91

Removed useless Jenkins Base Path

---

src/main/java/net/masterthought/cucumber/util/Util.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/util/CounterTest.java
src/test/java/net/masterthought/cucumber/util/UtilTest.java
src/test/resources/json/sample.json

Issue https://github.com/jenkinsci/cucumber-reports-plugin/issues/116

Invalid url caused fileName duplication

---

pom.xml

Downgrade Guava to 20.0 for java 7 compatibility.

Downgrade Guava to 20.0

---

src/main/java/net/masterthought/cucumber/EmptyReportable.java
src/main/java/net/masterthought/cucumber/Reportable.java
src/main/java/net/masterthought/cucumber/Trends.java
src/main/java/net/masterthought/cucumber/generators/OverviewReport.java
src/main/java/net/masterthought/cucumber/generators/StepsOverviewPage.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Result.java
src/main/java/net/masterthought/cucumber/json/support/Durationable.java
src/main/java/net/masterthought/cucumber/json/support/StepObject.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/main/resources/templates/generators/overviewSteps.vm
src/main/resources/templates/macros/json/duration.vm
src/main/resources/templates/macros/json/element.vm
src/main/resources/templates/macros/report/reportTable.vm
src/main/resources/templates/macros/report/statsTable.vm
src/test/java/net/masterthought/cucumber/EmptyReportableTest.java
src/test/java/net/masterthought/cucumber/ReportResultTest.java
src/test/java/net/masterthought/cucumber/ReportableBuilder.java
src/test/java/net/masterthought/cucumber/TrendsTest.java
src/test/java/net/masterthought/cucumber/generators/OverviewReportTest.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/json/ElementTest.java
src/test/java/net/masterthought/cucumber/json/FeatureTest.java
src/test/java/net/masterthought/cucumber/json/ResultTest.java
src/test/java/net/masterthought/cucumber/json/support/StepObjectTest.java
src/test/java/net/masterthought/cucumber/json/support/TagObjectTest.java

Duration is displayed for scenarios

---

src/test/java/net/masterthought/cucumber/generators/EscapeHtmlReferenceTest.java

Add unit tests for the sanitation case of the html escaping reference
handler.

Add additional unit test

---

src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/json/Result.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/test/java/net/masterthought/cucumber/ReportParserTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FailuresOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/json/FeatureTest.java
src/test/java/net/masterthought/cucumber/json/StepTest.java
src/test/resources/json/sample.json

Crash when step has no result section

---

src/main/java/net/masterthought/cucumber/Configuration.java
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/sorting/SortingFactory.java
src/main/java/net/masterthought/cucumber/sorting/SortingMethod.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportGenerator.java
src/test/java/net/masterthought/cucumber/generators/TrendsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/sorting/SortingFactoryTest.java
src/test/java/net/masterthought/cucumber/sorting/SortingMethod.java

Fixed class name typo.

---

src/main/java/net/masterthought/cucumber/util/Util.java
src/main/resources/templates/generators/overviewFeatures.vm

Extraneous closing span tag

---

src/main/java/net/masterthought/cucumber/Configuration.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java

Support for build number which is not integer

---

src/main/java/net/masterthought/cucumber/json/Hook.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/support/Resultsable.java
src/main/resources/templates/macros/json/hooks.vm
src/test/resources/json/sample.json

Adds support for output in hooks

---

src/main/java/net/masterthought/cucumber/util/Util.java
src/test/java/net/masterthought/cucumber/generators/OverviewReportTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/json/ElementTest.java
src/test/java/net/masterthought/cucumber/json/FeatureTest.java
src/test/java/net/masterthought/cucumber/json/ResultTest.java
src/test/java/net/masterthought/cucumber/json/support/StepObjectTest.java
src/test/java/net/masterthought/cucumber/json/support/TagObjectTest.java

Introduces another time format

---

src/main/java/net/masterthought/cucumber/generators/StepsOverviewPage.java
src/main/java/net/masterthought/cucumber/json/support/StepObject.java
src/main/resources/templates/generators/overviewSteps.vm
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/json/support/StepObjectTest.java

Issue jenkinsci/cucumber-reports-plugin/issues/203

Adds max duration for steps

---

src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/support/Argument.java
src/test/java/net/masterthought/cucumber/json/ArgumentTest.java
src/test/java/net/masterthought/cucumber/json/StepTest.java
src/test/resources/json/sample.json

Adds support for 'argument' field

---

pom.xml
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java

Remove log4j dependency and cleanup to use JUL
Related to: https://github.com/jenkinsci/cucumber-reports-plugin/issues/213

Use JUL instead of Log4j

---

src/main/java/net/masterthought/cucumber/json/Result.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/HookAssertion.java
src/test/java/net/masterthought/cucumber/json/ResultTest.java
src/test/resources/json/sample.json

- supports empty message
- adds tests for error message
- fixes older tests
Issue #234

ArrayOutOfBoundsException thrown when error_message = "\\n"

---

pom.xml

Updates dependencies

---

README.md

Adds badge for Known Vulnerabilities

---

README.md
pom.xml
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/json/support/StatusCounter.java
src/main/resources/templates/macros/json/element.vm
src/main/resources/templates/macros/json/hooks.vm
src/main/resources/templates/macros/json/steps.vm
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/ElementAssertion.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/StepAssertion.java
src/test/java/net/masterthought/cucumber/json/StepTest.java
src/test/resources/json/sample.json

Issue https://github.com/damianszczepanik/maven-cucumber-reporting/issues/100#issuecomment-398284888

Support for BeforeStep and AfterStep hooks in Cucumber-JVM 3.x.x

---

src/main/java/net/masterthought/cucumber/Configuration.java
src/main/java/net/masterthought/cucumber/EmptyReportable.java
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/Reportable.java
src/main/java/net/masterthought/cucumber/generators/OverviewReport.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/main/java/net/masterthought/cucumber/reducers/ReducingMethod.java
src/main/java/net/masterthought/cucumber/sorting/FeaturesAlphabeticalComparator.java
src/main/resources/templates/macros/report/reportTable.vm
src/main/resources/templates/macros/report/statsTable.vm
src/test/java/net/masterthought/cucumber/EmptyReportableTest.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportGenerator.java
src/test/java/net/masterthought/cucumber/ReportableBuilder.java
src/test/java/net/masterthought/cucumber/generators/OverviewReportTest.java
src/test/java/net/masterthought/cucumber/generators/TrendsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/json/FeatureTest.java
src/test/java/net/masterthought/cucumber/json/support/TagObjectTest.java
src/test/java/net/masterthought/cucumber/sorting/FeaturesAlphabeticalComparatorTest.java

jenkinsci/cucumber-reports-plugin/pull/98

Read and combine all identically named features into one json report

---

src/main/java/net/masterthought/cucumber/Configuration.java
src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/reducers/ReducingMethod.java
src/test/java/net/masterthought/cucumber/json/FeatureTest.java
src/test/java/net/masterthought/cucumber/sorting/FeaturesAlphabeticalComparatorTest.java

Issue jenkinsci/cucumber-reports-plugin/issues/261

Restores filename postfix to distinguish redundant features

---

src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/reducers/ReducingMethod.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/json/FeatureTest.java

(restores feature presented for version 3.x)

Features with the same ID are stored in different files by default

---

src/main/java/net/masterthought/cucumber/Configuration.java
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/resources/templates/macros/page/navigation.vm
src/test/java/net/masterthought/cucumber/ConfigurationTest.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java

Issue jenkinsci/cucumber-reports-plugin/pull/247

Adds possibility to disable trends page

---

src/main/resources/templates/js/trends-chart.js.vm

- steps were presented as scenarios
Issue #765  #783

Trend does not display the correct passing amount when there are morefailures than passes

---

src/main/java/net/masterthought/cucumber/Configuration.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/presentation/PresentationMode.java
src/main/resources/templates/macros/json/element.vm
src/main/resources/templates/macros/json/hooks.vm
src/main/resources/templates/macros/json/steps.vm
src/test/java/net/masterthought/cucumber/ConfigurationTest.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/ErrorPageTest.java
src/test/java/net/masterthought/cucumber/generators/FailuresOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeatureReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TrendsOverviewPageTest.java

Add possibility to decide if the scenarios are expanded or not

---

src/main/resources/templates/macros/report/expandAllButtons.vm

Avoid showing the horizontal scrollbar on Failures page

Avoid showing the horizontal scrollbar

---

src/main/java/net/masterthought/cucumber/generators/TagsOverviewPage.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageTest.java

Excluded tags are not displayed at summary

---

src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/json/Hook.java
src/main/java/net/masterthought/cucumber/reducers/ReducingMethod.java
src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/main/resources/templates/macros/json/hooks.vm
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/ErrorPageTest.java
src/test/java/net/masterthought/cucumber/generators/FailuresOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeatureReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TrendsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/json/HookTest.java
src/test/java/net/masterthought/cucumber/util/UtilTest.java

Skip empty hooks

---

src/main/resources/templates/generators/overviewFailures.vm
src/main/resources/templates/generators/overviewFeatures.vm
src/main/resources/templates/generators/overviewTags.vm
src/main/resources/templates/generators/overviewTrends.vm
src/main/resources/templates/generators/reportFeature.vm
src/main/resources/templates/generators/reportTag.vm
src/main/resources/templates/head.vm
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/resources/json/sample.json

Fixed problems caused during HTML page generation

---

src/main/java/net/masterthought/cucumber/json/Embedding.java
src/main/java/net/masterthought/cucumber/json/deserializers/EmbeddingDeserializer.java
src/main/resources/templates/macros/json/embeddings.vm
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/ReportAssertion.java
src/test/java/net/masterthought/cucumber/json/EmbeddingTest.java
src/test/resources/json/sample.json

Cucumber 4.6.0 introduced support for embeddings with custom names. This pull request is to handle named embeddings in reports. Please see also [cucumber-jvm #1692](https://github.com/cucumber/cucumber-jvm/issues/1692).

Support named embeddings

---

src/test/java/LiveDemoTest.java

Issue damianszczepanik/maven-cucumber-reporting/issues/162

Add reference to Github

---

src/main/resources/templates/js/features-chart.js.vm
src/main/resources/templates/js/scenarios-chart.js.vm

Improve consistency between elements in items in feature carousel.

Consistence items in carousel

---

src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java

Looks like the wrong config value was used.

Fix "Hide Empty Hooks" configuration

---

pom.xml
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/generators/EscapeHtmlReference.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/EscapeHtmlReferenceTest.java

Reverts damianszczepanik/cucumber-reporting#881

Revert "Update velocity to 2.1"

---

pom.xml
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/generators/EscapeHtmlReference.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/EscapeHtmlReferenceTest.java

Reverts damianszczepanik/cucumber-reporting#883

Revert "Revert "Update velocity to 2.1""

---

src/main/java/net/masterthought/cucumber/ReportResult.java
src/main/java/net/masterthought/cucumber/reducers/ReportFeatureAppendableMerger.java
src/main/java/net/masterthought/cucumber/reducers/ReportFeatureByIdMerger.java
src/main/java/net/masterthought/cucumber/reducers/ReportFeatureMerger.java
src/main/java/net/masterthought/cucumber/reducers/ReportFeatureMergerFactory.java
src/test/java/net/masterthought/cucumber/ReportGenerator.java
src/test/java/net/masterthought/cucumber/reducers/ReportFeatureAppendableMergerTest.java
src/test/java/net/masterthought/cucumber/reducers/ReportFeatureByIdMergerTest.java
src/test/java/net/masterthought/cucumber/reducers/ReportFeatureMergerFactoryTest.java

Hi, @damianszczepanik !
Sorry for a huge delay. I was out of the web :)
This is a part of https://github.com/damianszczepanik/cucumber-reporting/pull/880.
As you said before PR#880 is too large and you asked me to split it to a smaller parts.
https://github.com/damianszczepanik/cucumber-reporting/pull/880#discussion_r339325932
Please, review when you have a chance.
Thx!

Introduced a ReportFeatureMerger interface for a better extensibility

---

src/main/java/net/masterthought/cucumber/reducers/ReportFeatureMerger.java
src/main/java/net/masterthought/cucumber/reducers/ReportFeatureWithRetestMerger.java
src/test/java/net/masterthought/cucumber/ReportResultMergeTest.java
src/test/java/net/masterthought/cucumber/reducers/ReportFeatureWithRetestMergerTest.java

Hi, @damianszczepanik ! sorry, I didn't expect that you are going to create a new version such fast. There is a PR with bunch of unit tests for the gaps from previous PR. Could you take a look?

Unit tests for ReportFeatureWithRetestMerger

---

src/main/resources/css/cucumber.css
src/main/resources/templates/macros/json/stepName.vm

Introducing new line or separators within steps of the report

---

src/main/java/net/masterthought/cucumber/json/Embedding.java
src/test/java/net/masterthought/cucumber/json/EmbeddingTest.java

Support for various types of archives. Otherwise the ending of the file is always ".unknown".

Support embeddings of archives (zip, gzip, tar, bz2)

---

src/main/java/net/masterthought/cucumber/json/Step.java
src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java
src/test/java/net/masterthought/cucumber/util/StepNameFormatterTest.java
src/test/resources/json/sample.json

Incorrect stepname formatting while including empty arguments

---

src/main/resources/templates/generators/overviewFeatures.vm
src/main/resources/templates/generators/overviewTags.vm
src/main/resources/templates/generators/reportFeature.vm
src/main/resources/templates/macros/report/reportHeader.vm
src/main/resources/templates/macros/report/reportTable.vm
src/main/resources/templates/macros/report/statsTable.vm

Removes dead code about parallel testing

---

src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/presentation/PresentationMode.java
src/main/resources/templates/macros/report/reportHeader.vm
src/main/resources/templates/macros/report/statsTable.vm
src/test/java/LiveDemoTest.java
src/test/java/net/masterthought/cucumber/ReportParserTest.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/ErrorPageTest.java
src/test/java/net/masterthought/cucumber/generators/FailuresOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeatureReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TrendsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/json/FeatureTest.java

Enable parallel testing

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/generators/TagsOverviewPage.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Tag.java
src/main/java/net/masterthought/cucumber/json/deserializers/TagsDeserializer.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TagsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/json/TagTest.java
src/test/java/net/masterthought/cucumber/json/deserializers/EmbeddingDeserializerTest.java
src/test/java/net/masterthought/cucumber/json/deserializers/TagsDeserializerTest.java

Disable or speed up "Tags" page

---

.travis.yml
README.md

Solves problem with sonar:
Not authorized. Please check the properties sonar.login and sonar.password.
according to: https://community.sonarsource.com/t/error-not-authorized-please-check-the-properties-sonar-login-and-sonar-password/21076/8

Sonar test

---

src/test/java/LiveDemoTest.java

Add more descriptive sample

---

src/main/java/net/masterthought/cucumber/json/Element.java

Issue https://github.com/jenkinsci/cucumber-reports-plugin/issues/364#

setNotFailingStatuses should respect hooks

---

src/main/java/net/masterthought/cucumber/json/Embedding.java
src/test/java/net/masterthought/cucumber/json/EmbeddingTest.java

Dear Damian, I read your [contributing guidlines](https://github.com/damianszczepanik/cucumber-reporting/blob/master/CONTRIBUTING.md) and would like to offer an implementation of the issue #969 (Improve Extensions for Report Attachment).
My first pull request did not test all of the decision branches of the new code. Now, it does.
Please let me know if I shall improve anything else of that solution.
Thank you in advance, Stefan.

969 improve extensions for report attachment

---

src/main/java/net/masterthought/cucumber/generators/FailuresOverviewPage.java

When scenario has failed hooks but passing steps then failure report was empty

---

src/main/java/net/masterthought/cucumber/Configuration.java
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/resources/templates/head.vm
src/main/resources/templates/headers.vm
src/test/java/net/masterthought/cucumber/ConfigurationTest.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/ErrorPageTest.java
src/test/java/net/masterthought/cucumber/generators/FailuresOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeatureReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TrendsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/HeadAssertion.java

Hi,
this is a small addition which allows you to include custom js and css files into the final report. This allows a bit of customization of the report without introducing a full theming option.

Include custom JS and CSS in report

---

src/test/java/LiveDemoTest.java
src/test/resources/css/stackoverflow-light.min.css
src/test/resources/js/LICENSE_highlightjs
src/test/resources/js/enable-highlighting.js
src/test/resources/js/highlight.min.js
src/test/resources/json/sample.json

This adds syntax highlighting to the livedemo for JSON and XML attachments.
It uses highlightjs.org.

Add custom js to livedemo

---

src/main/java/net/masterthought/cucumber/json/deserializers/StatusDeserializer.java
src/main/java/net/masterthought/cucumber/util/Util.java
src/test/java/net/masterthought/cucumber/generators/integrations/PageIntegrationTest.java
src/test/java/net/masterthought/cucumber/json/deserializers/StatusDeserializerTest.java

jenkinsci/cucumber-reports-plugin/issues/409

Report does not change locale

---

src/main/java/net/masterthought/cucumber/generators/FeatureReportPage.java
src/main/resources/templates/macros/report/reportTable.vm
src/test/java/net/masterthought/cucumber/generators/FeatureReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java

Qualifier missing from the report-feature html

---

pom.xml
src/main/java/net/masterthought/cucumber/json/Embedding.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/EmbeddingAssertion.java

especially not use plexus utils as that is for maven only.

[base64] Use java natively

---

src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/PageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/WebAssertion.java

java 8 introduced Objects to string which replaces need for commons lang version.

[java] Try to use more java directly rather than commons*

---

src/test/java/net/masterthought/cucumber/ReportBuilderTest.java

Fix for commons-io:commons-io from 2.11.0 to 2.15.1

---

pom.xml

Added in 00b7a33711720625fb8a9a6e9b5857de2f1f4d10

Reverts partially 00b7a33711720625fb8a9a6e9b5857de2f1f4d10 about guava dependency

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java

1. **Extract Method**: `buildFullPath()` encapsulates path construction
2. **Rename Variable**: Clarified parameters (`resourceType`, `fileName`)
3. **Introduce Explaining Variable**: `fullPath` documents intermediate result
- All existing tests pass (`mvn clean test`)
- File output structure remains unchanged

Refactor: Extract method, rename params, and introduce explaining variable

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportParser.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java

partially reverts  #1265 06d0488464784a3f8de533228b2d06cf2c180d62

Fixes support for bigger report File
