src/main/resources/templates/featureOverview.vm
src/main/resources/templates/tagOverview.vm

The project name is not shown in the report. Which causes a problem if we have multiple projects and each publishing the reports. With this change it becomes easier for the user to identify the project for which the report is intended

UPdated for showing project name in report if the build is from Jenkins

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/resources/templates/featureOverview.vm
src/main/resources/templates/featureReport.vm
src/main/resources/templates/tagOverview.vm
src/main/resources/templates/tagReport.vm

- since report has no information about previous build I've added link to the header when build number > 1
- previous link directs to the same page of previous build (not the main) so comparing results is easier
Issue #33

Added lint to previous build:

---

src/main/resources/templates/featureOverview.vm
src/main/resources/templates/featureReport.vm
src/main/resources/templates/tagOverview.vm
src/main/resources/templates/tagReport.vm

From now not only table header and results summary have background color but also each cell with failures/pending/undefined/... It's easier to find failures if the report is big and only a few failures happened.

Added background color for those cells of table that have values > 0.

---

src/main/java/net/masterthought/cucumber/json/Step.java
src/main/resources/styles/reporting.css
src/test/java/net/masterthought/cucumber/StepTest.java

I've added css class for wrapping error message in a parent div.
Before:
After:

Wrapping step error message in div.

---

src/main/java/net/masterthought/cucumber/generators/ErrorPage.java
src/main/resources/templates/pages/errorPage.vm
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/178%23issuecomment-138005106%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/178%23issuecomment-138005106%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6086.65%25%60%5Cn%3E%20Merging%20%2A%2A%23178%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%607710e65%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23178%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D …

Show full stacktrace as html message when crash happens

---

.travis.yml
src/main/java/net/masterthought/cucumber/json/Step.java
src/main/resources/templates/pages/featureReport.vm
src/test/java/net/masterthought/cucumber/StepTest.java

This fixes a problem with parsing of output field that is an array of String, that was introduced in #188, now both single and double array is parsable.
I've also added 'sudo: required' in .travis.yml since now the default for new repositories is 'sudo: false', and my builds were broken.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/200%23issuecomment-143474403%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/200%23issuecomment-143476551%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/200%23issuecomment-143478664%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/200%23issuecomment-143491758%22%2C%20%22https%3A//github.com/damiansz …

Fixed parsing of Step output field that is an array of String

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java

I added some code to read the zip-file as a class path resource and copy in to a temporary file before unzipping it. The reason is that when running this from e.g. a maven plugin it is not possible to build a URI that points to the zip-resources inside a jar file. 
I had problems getting maven-cucumber-reporting to run before this, but with this change it works fine.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/215%23issuecomment-154734346%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/215%23issuecomment-154734346%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5 …

Copied zip-resources to temporary file before extracting them.

---

src/main/java/net/masterthought/cucumber/Background.java
src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/generators/FeatureReportPage.java
src/main/java/net/masterthought/cucumber/generators/TagReportPage.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/Scenario.java
src/main/java/net/masterthought/cucumber/json/Tag.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java

Issue #122
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/217%23issuecomment-155218460%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/217%23issuecomment-155219887%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/217%23issuecomment-155218460%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22This%20is%20first%20step%20of%20making%20generation%20process%20shorter%20-%20some%20methods%20with%20O%28n%29%20complexity%20were%20executed%20all%20the%20time.%20Some%20other%20are%20still%20there%20but%20it%20takes%20time%20to%20make%20sure%20that%20there%20is%20no%20regression%22%2C%2 …

Reducing complexity + code clean-up

---

src/main/java/net/masterthought/cucumber/ReportInformation.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/main/resources/templates/pages/featureOverview.vm
src/main/resources/templates/pages/featureReport.vm
src/main/resources/templates/pages/tagOverview.vm
src/main/resources/templates/pages/tagReport.vm
src/test/java/net/masterthought/cucumber/FeatureTest.java

Issue #122
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/223?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/223'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Methods in TagObject count values/counters/stats at once, not each me were invoked

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java

** CID 153787:  FindBugs: Bad practice  (FB.RV_RETURN_VALUE_IGNORED_BAD_PRACTICE)
/src/main/java/net/masterthought/cucumber/ReportBuilder.java: 184 in net.masterthought.cucumber.ReportBuilder.copyResource(java.lang.String, java.lang.String)()
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/225?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/225'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fixed coverity issue:

---

src/main/java/net/masterthought/cucumber/json/Step.java

Issue #252
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/253%23issuecomment-161744485%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/253%23issuecomment-161744485%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6088.23%25%60%5Cn%3E%20Merging%20%2A%2A%23253%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.15%25%2A%2A%20as%20of%20%5B%60d03b104%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23253%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D% …

Error message is not formatted

---

src/main/java/net/masterthought/cucumber/json/support/StepObject.java
src/main/resources/templates/generators/stepsOverview.vm
src/test/java/net/masterthought/cucumber/generators/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/helpers/TableRowAssertion.java
src/test/resources/json/sample.json

If the duration is > 1 second, then the time formatting can confuse tablesorter's sorting. So instead, we add the unformatted time values as a data attribute. tablesorter will automatically detect and pickup these values and use them to sort.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/413%23issuecomment-214944697%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/413%23issuecomment-214971946%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/413%23issuecomment-214983238%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/413%23issuecomment-214944697%22%2C%20 …

Correctly sort columns with durations

---

src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/support/TagObject.java
src/main/java/net/masterthought/cucumber/reports/OverviewReport.java
src/main/java/net/masterthought/cucumber/reports/Reportable.java
src/main/resources/templates/macros/report/reportTable.vm
src/main/resources/templates/macros/report/statsTable.vm
src/test/java/net/masterthought/cucumber/FeatureTest.java
src/test/java/net/masterthought/cucumber/ReportInformationTest.java
src/test/java/net/masterthought/cucumber/TagsTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/json/support/StepObjectTest.java

Implementing the rest of #401 
Added raw duration values to features and tags overview pages for correct sorting capability.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/414%23issuecomment-215167778%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/414%23discussion_r61305828%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/414%23issuecomment-215167778%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5Bcc-pull%5D%20is%20%2A%2A60.61%25%2A%2A%5Cn%3E%20Merging%20%5B%23414%5D%5Bcc-pull%5D%20into%20%5Bmaster%5D%5Bcc-base-branch%5D%20will%20increa …

Implement correct time sorting fix for features and tags overview pages

---

src/main/resources/css/reporting.css
src/main/resources/templates/head.html
src/main/resources/templates/macros/report/reportHeader.vm

Sorting the "Scenario" and "Steps" column groups doesn't make sense
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/423?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/423'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Prevent top row headers from sorting

---

src/main/resources/css/reporting.css
src/main/resources/templates/generators/stepsOverview.vm
src/main/resources/templates/macros/report/statsTable.vm

Makes it easier to see what the user is current hovering cursor over. Helpful when the table is very long. This is not applied to the report table, since it's basically just one row.
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/429?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/429'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Add hover effect to stats and steps table rows

---

src/main/resources/templates/macros/report/elements.vm

Smoothly expand and collapse backgrounds and scenarios. They weren't expanding smoothly because they were contained in a span, instead of a div like the steps.
<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/430?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/430'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Make background/scenario expand/collapse smoothly

---

src/main/resources/templates/macros/report/embeddings.vm

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/427%23issuecomment-216075260%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/427%23discussion_r61710598%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/427%23issuecomment-216744094%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/427%23issuecomment-216750054%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/427%23issuecomment-216075260%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5Bcc-pull%5D%20is%20%2A%2A69.47%25%2A%2A%5Cn%3E%20Merging%20%5B% …

Don't add embedded HTML if there's no embedded content

---

src/main/resources/css/reporting.css
src/main/resources/templates/macros/report/embeddings.vm
src/main/resources/templates/macros/report/message.vm

Was using custom JS to expand and collapse. Since bootstrap's collapse
was used recently for feature/scenario/step/hook collapsing, do the same
so the code is more consistent.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/424%23issuecomment-216073078%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/424%23discussion_r61711718%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/424%23issuecomment-216124483%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/424%23issuecomment-216744634%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/424%23issuecomment-218573019%22%2C%20%22https%3A//github.com/damianszczepanik/cucu …

Use bootstrap collapse function for message/embed content

---

src/main/resources/templates/headers.vm
src/main/resources/templates/macros/report/docstring.vm
src/main/resources/templates/macros/report/steps.vm
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/StepsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/DocStringAssertion.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/StepAssertion.java
src/test/java/net/masterthought/cucumber/json/ResultTest.java
src/test/java/net/masterthought/cucumber/json/RowTest.java
src/test/java/net/masterthought/cucumber/json/support/TagObjectTest.java
src/test/resources/json/sample.json

In the current version (2.3.0), if user defined some doc strings in their scenario steps, then they are simply ignored by the generator, thus not visible in the report.
It would be nice to have them show up in the report as well. For instance:
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/458%23issuecomment-223031362%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/458%23discussion_r65406569%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/458%23discussion_r65406877%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/458%23discussion_r65407167%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/458%23discussion_r …

Add support for step doc string.

---

src/main/java/net/masterthought/cucumber/generators/FailuresOverviewPage.java
src/main/resources/templates/generators/failuresOverview.vm
src/test/java/net/masterthought/cucumber/ReportGenerator.java
src/test/java/net/masterthought/cucumber/generators/FailureOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/FailuresOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FailuresOverviewPageIntegrationTest.java
src/test/resources/json/failures.json

Only show failed scenarios.
Tested with multiple feature files in a single test run:
* Feature file with 1 failure and 1 pass
* Feature file with 2 failures and 1 pass
* Feature file with 1 pass
Only failed scenarios shown in the failures overview page.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/476%23issuecomment-226975649%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/476%23issuecomment-226976749%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/476%23discussion_r67615412%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/476%23discussion_r67615458%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/476%23 …

Fix Failures Overview page

---

src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/util/Counter.java
src/main/resources/templates/macros/report/docstring.vm
src/main/resources/templates/macros/report/element.vm
src/main/resources/templates/macros/report/hooks.vm
src/main/resources/templates/macros/report/message.vm
src/main/resources/templates/macros/report/output.vm
src/main/resources/templates/macros/report/steps.vm
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/ErrorPageTest.java
src/test/java/net/masterthought/cucumber/generators/FailuresOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeatureReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/FeaturesOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/StepsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagReportPageTest.java
src/test/java/net/masterthought/cucumber/generators/TagsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/util/CounterTest.java

When multiple error messages are exactly the same, the UI only
expand/collapses the first message box on the page. This is due to the
same hash codes. An incrementing counter was appended to the IDs to make
them unique.
https://github.com/damianszczepanik/cucumber-reporting/issues/471
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/477%23issuecomment-226978122%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/477%23issuecomment-226992583%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/477%23issuecomment-227010638%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/477%23issuecomment-229512652%22%2C%20%22https%3A//github.com/damianszcze …

Fix broken message boxes

---

.travis.yml

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/525?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/525'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Updated workaround for buffer overflow in Inet4AddressImpl::getLocalHostName

---

src/main/resources/css/cucumber.css

```
Feature: preserving whitespaces in HTML output
As a user
I would like to preserve white spaces in this text
In order to have the output more similar to the .feature file
Scenario: Running this feature (wow, meta)
When I run this feature with HTML output
Then the output should preserve the new lines in the description
```
[Graciously stolen from cucumber-html issue #29](https://github.com/cucumber/cucumber-html/issues/29)

Preserving whitespaces in HTML output

---

src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/generators/EscapeHtmlReference.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Embedding.java
src/main/java/net/masterthought/cucumber/json/Result.java
src/main/resources/templates/generators/errorpage.vm
src/main/resources/templates/macros/json/element.vm
src/main/resources/templates/macros/json/embeddings.vm
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/EscapeHtmlReferenceTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FailuresOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/EmbeddingAssertion.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/StepAssertion.java
src/test/java/net/masterthought/cucumber/json/ElementTest.java
src/test/java/net/masterthought/cucumber/json/EmbeddingTest.java
src/test/java/net/masterthought/cucumber/json/FeatureTest.java
src/test/java/net/masterthought/cucumber/json/ResultTest.java

It is preferable to escape HTML through the template engine over escaping it at in
the template. This ensures none can be forgotten on accident. The unfortunate side
effect of this is that it no longer possible to  provide html as an argument in a
macro. This leads to some duplication in embeddings.vm
Existing methods to escape html have been removed.

 Escape HTML using the velocity engine

---

src/main/resources/css/cucumber.css
src/main/resources/templates/macros/json/embeddings.vm
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/FeatureReportPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/EmbeddingAssertion.java
src/test/resources/json/sample.json

It preferable to allow the browser to render embedded  html documents. To ensure this is done safely the html is placed in a sandboxed iframe. The html is embeded in the srcdoc as recommend by  the w3c[1]. The src attribute is provided as a backup for legacy browsers.
Additionally because the cucumber-reporting-plugin must necessarily serve embedded html documents from the same domain as the report  the download link will now force a popup to open. While this can not prevent the embedded content from tricking the user into opening it directly, it at least mitigates some of the issues mentioned by the w3c[1].
1. https://www.w3.org/TR/html5/embedded-content-0.html#the-iframe-element

Embed html in a sandboxed iframe

---

pom.xml
src/main/java/net/masterthought/cucumber/generators/EscapeHtmlReference.java
src/main/resources/templates/macros/page/classifications.vm
src/test/java/net/masterthought/cucumber/generators/integrations/FeaturesOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/TableRowAssertion.java

Trusted content such as classifications may contain urls that should not be escaped.
Any reference prefixed with $\_sanitize_ will not be escaped but sanitized instead.

Santize trusted content

---

src/main/resources/css/cucumber.css
src/main/resources/templates/macros/json/embeddings.vm

Text and xml embedding were surounded by a border while other plain elements such as errors
and image attachment did not. This looked rather messy.

Show text embedding without superfluous borders

---

src/main/resources/css/cucumber.css
src/main/resources/templates/macros/json/hooks.vm
src/main/resources/templates/macros/json/output.vm
src/test/java/net/masterthought/cucumber/generators/integrations/helpers/OutputAssertion.java

As reported in https://github.com/jenkinsci/cucumber-reports-plugin/issues/145 pull request #594
broke formatting of output messages by adding white-space-normal to the pre
block. Presumably to solve the formatting issues caused by adding new lines
around the span.
This has been resolved removing the  white-space-normal class and using a single
line in the template. The span has been replaced with a p to ensure there is a
significant distance between different output messages.

Restore whitespace significant formatting for message

---

src/main/java/net/masterthought/cucumber/json/Embedding.java
src/test/java/net/masterthought/cucumber/json/EmbeddingTest.java

Currently the PDF embedding is downloaded as "unknown":
With this commit the PDF embedding will be downloaded as "PDF document":

Support PDF embedding with `.pdf` extension

---

src/main/java/net/masterthought/cucumber/json/deserializers/EmbeddingDeserializer.java
src/test/java/net/masterthought/cucumber/generators/FeatureReportPageTest.java
src/test/resources/json/sample.json

Fixes jenkinsci/cucumber-reports-plugin#193 by conditionally trying to load the mime type of an embedding from the v3 location, if not found it will fall back to v2.  Also adds tests for the same.
Happy to make any amends necessary.

Support screenshots in v2 and v3 reports

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java

The `ReportBuilder` kept a list of pages to generate for no obvious reason. This change removes this list and collects and generates pages in a single pass.

Reduce memory use when generating pages

---

src/main/resources/log4j2.properties

Issue #675 was closed because of missing functional impact.
But that ERROR log message still is there and initially confuses every colleague looking at the output.
A simple fix would be supplying an appropriate LOG4J config file (like you do already for unit tests).

Proposed fix for damianszczepanik/cucumber-reporting#675

---

pom.xml

Per #721, update jackson-databind from v2.8.6 to v2.8.11.1 to address [CVE-2018-7489](https://nvd.nist.gov/vuln/detail/CVE-2018-7489), a deserialization flaw with CVSS v3.0 Base Score of 9.8 (critical)
The fix for CVE-2018-7489 also addresses CVE-2017-15095 and CVE-2017-7525
Whilst the fix is also available in jackson-databind v2.9.5,  v2.8.11.1 was selected so as to be conservative (minimize risk) and because v3.x should be released shortly.

Update jackson-databind to address CVE-2018-7489

---

src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java
src/test/java/net/masterthought/cucumber/util/StepNameFormatterTest.java
src/test/resources/json/sample.json

When a step has an optional matching argument and the argument is not
matched, the JSON report has an empty object in place of that argument
in the match array. A check has been added to skip those empty
arguments.

Fixes #781: NPE with optional step arguments.

---

src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java
src/test/java/net/masterthought/cucumber/util/StepNameFormatterTest.java
src/test/resources/json/sample.json

When there is an empty match at the end of string, such as
@Given("^the card is valid(.*)$")
(with not extra text after "valid), an ArrayIndexOutOfBounds was
generated.

Fixes error when there is an empty match at end of string. Closes #789.

---

README.md
src/main/java/net/masterthought/cucumber/Configuration.java
src/main/java/net/masterthought/cucumber/json/Element.java
src/main/java/net/masterthought/cucumber/json/Feature.java
src/main/java/net/masterthought/cucumber/json/support/StatusCounter.java
src/main/java/net/masterthought/cucumber/reducers/ReducingMethod.java
src/test/java/net/masterthought/cucumber/ConfigurationTest.java
src/test/java/net/masterthought/cucumber/json/support/ResultsableBuilder.java
src/test/java/net/masterthought/cucumber/json/support/comparators/StatusCounterTest.java

Allow undefined and pending steps to not fail

---

src/main/resources/templates/macros/json/embeddings.vm
src/main/resources/templates/macros/json/output.vm

@damianszczepanik - as discussed, this PR adds capability to expand output and embed contents when EXPAND_ALL_STEPS config is used.
resolves #872

expand output and embed contents when EXPAND_ALL_STEPS config is used

---

pom.xml
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/main/java/net/masterthought/cucumber/generators/EscapeHtmlReference.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/EscapeHtmlReferenceTest.java

Hi there
I've been having some problems with version conflicts between the gradle form of this plugin and owasp gradle plugin as both are using different versions of velocity and I can't seem to get the gradle buildscript to do what I want dependency wise. 
Velocity version is currently at 2.1 (which is what the owasp plugin is using) so I've updated this, removed a redundant depedency on velocity-tools (looks like it was used for the escape tool along while back) and fixed a few deprecation warnings wrt property name changes :-)
The generated demo report looks identical to the hosted one and all tests passed locally.

Update velocity to 2.1

---

pom.xml

Hi, @damianszczepanik !
This is a downgrade of com.fasterxml.jackson.datatype:jackson-datatype-jsr310 to 2.9.10 to avoid an issue with Enforser plugin in the following project https://github.com/jenkinsci/cucumber-reports-plugin

Sync version of jackson dependencies up to 2.10.1

---

src/main/java/net/masterthought/cucumber/json/Embedding.java
src/test/java/net/masterthought/cucumber/json/EmbeddingTest.java

Support for following mime type and returning it's file extension added in `Embedding.java`
| Document Kind | Extension | Mime Type |
| ----------------- | ----------- | ------------ |
| Microsoft Excel | `.xls` | `application/vnd.ms-excel` |
| Microsoft Excel (OpenXML) | `.xlsx` | `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` |
Following `Tests` Added for above changes.
| File | Test Function |
| ---- | -------------- |
| `EmbeddingTest.java` | `getExtension__OnApplicationOpenXMLFormatsOfficeDocumentSpreadsheetMimeType_ReturnsXlsx()` |
| `EmbeddingTest.java` | `getExtension__OnApplicationVNDMsExcelMimeType_ReturnsXls()` |

Embedding support for Excel files (xlsx and xls) added

---

pom.xml

Partially reverts commit 09a6968451c009e1f031b9e6d7b760efe0af1fef.
Leave support for JDK11 and compatibility with JDK8

Migrate to JDK 11

---

src/main/java/net/masterthought/cucumber/ReportParser.java
src/test/java/net/masterthought/cucumber/ReportParserTest.java

Not quite sure what happened, as the PR appears to have been still open but then had unresolved history with master. Updating https://github.com/damianszczepanik/cucumber-reporting/pull/1046 forced it to close itself.
This amends the tests from the aforementioned PR, anyway.

Fix error messages + tests

---

pom.xml

Jackson 2.13.2.20220328 upgrades jackson-databind from 2.13.2 to 2.13.2.2
fixing Denial of Service (DoS):
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518

Jackson 2.13.2.20220328 (CVE-2020-36518)

---

src/main/resources/templates/macros/json/embeddings.vm

Fix issue where download links are not accessible from within embedded HTML.

allow-downloads in html embedding

---

pom.xml

Upgrade jsoup from 1.15.1 to 1.15.3. This fixes this vulnerability:
The jsoup cleaner may incorrectly sanitize crafted XSS attempts if SafeList.preserveRelativeLinks is enabled
https://github.com/jhy/jsoup/security/advisories/GHSA-gp7f-rwcx-9369

jsoup 1.15.3 (CVE-2022-36033)

---

pom.xml
src/main/java/net/masterthought/cucumber/ReportParser.java

When the commons-colllections dependency was updated to v4 the only(!) used import was updated wrongly.
This resulted in `NoSuchMethods` exception in certain classpath configurations.
```
[...]
Caused by: java.lang.NoSuchMethodError: 'boolean org.apache.commons.lang3.ObjectUtils.isNotEmpty(java.lang.Object)'
at net.masterthought.cucumber.ReportParser.parseClassificationsFiles(ReportParser.java:129)
at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:94)
[...]
```
I suggest to simply drop the dependency completely, as it is only used a single time.

Remove dependency to commons-collections4

---

pom.xml

This addresses the following CVE's:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42003
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42004

Upgrade Jackson dependency version to address vulnerabilities

---

pom.xml
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportParserTest.java
src/test/java/net/masterthought/cucumber/TrendsTest.java
src/test/java/net/masterthought/cucumber/generators/AbstractPageTest.java
src/test/java/net/masterthought/cucumber/generators/TrendsOverviewPageTest.java
src/test/java/net/masterthought/cucumber/generators/integrations/TrendsOverviewPageIntegrationTest.java
src/test/java/net/masterthought/cucumber/json/ArgumentTest.java
src/test/java/net/masterthought/cucumber/json/FeatureTest.java
src/test/java/net/masterthought/cucumber/json/support/ResultsableBuilder.java
src/test/java/net/masterthought/cucumber/sorting/FeaturesAlphabeticalComparatorTest.java
src/test/java/net/masterthought/cucumber/sorting/SortingFactoryTest.java

As the current maintainer of jmockit, I highly advice not using jmockit any more.  The original author vanished back in 2020 and its a considerable mess thus your own comment stuck on old.  While deencapsulation is now added back in current release, its native replacement is whiteboxing and this project already used powermock.  Switching was trivial.

[tests] Replace jmockit with powermock whitebox and use version 2.0.9 of powermock

---

src/test/java/net/masterthought/cucumber/json/EmbeddingTest.java

This pull request introduces a new test case in the `EmbeddingTest` class, specifically in the `getExtension` method. The test, named `getExtension_UsesExtensionFromNameWhenMIMETypeIsUnknown`, verifies that the method correctly retrieves the file extension from the name when the MIME type is unknown. This improvement makes sure our code handles unknown file types more effectively and adds to the overall coverage of our code tests.
Your review of the changes is appreciated. Thank you!

Add test for getExtension method in Embedding class

---

.github/workflows/build.yml
pom.xml

The profile needs are to allow java 17 or higher.  To test, remove them, run build with java 17, see first issue, then add back until working.
Added GHA to matrix for java 17 and 21.  This should also work with jdk 22 as well now.

Allow builds to run with java 17 or 21

---

pom.xml
src/main/java/net/masterthought/cucumber/ReportBuilder.java

mainly due to test sending incredibly wrong value on purpose that old version just stated io exception on but now is illegal argument exception.

[io] Update commons io to 2.11.0 and fix code to handle illegal argument exception

---

pom.xml

note, a better longer term fix would be to stop using this parent.  Sonatype deprecated it and retired it many years ago.  They suggest just incorporating items internally.

Bump oss-parent to last ever version '9', add relativePath so it forces look to m2 repo

---

pom.xml
src/main/java/net/masterthought/cucumber/ReportParser.java

Original commons configuration had dependency on commons bean utils which is used by a test case via sun proxy.  Set that as test scope.  Moved the compile scoped commons items up to area with other commons to be clear what is test vs compile scope.
Note duplicate keys cannot generally occur in newer version but a test is expecting it so code added to allow such a condition to occur.  That may need to be removed instead and test removed.  General idea here though was to handle exactly as it does right now.

Upgrade to commons configuraton 2 and adjust location of dependencies for clarity (compile vs test)

---

pom.xml

This resolves newer jdk 19+ that suggests java will block this in the future from dynamically adding.  Therefore this is no longer dynamically added both for lower jdks as well as jdk 17+
How and where byte-buddy is used?
- mockito
- assertj
While the agent is the concern here, we need to make sure both stay in sync as they are well known to fail if out of sync on more recent versions (such as latest here) due to the versions mockito / assertj are using.  That is even if its true, assertj just released new and is up to date now.
For an extremely lengthy discussion on it as well as links/mentions to the JSR involved, see https://github.com/mockito/mockito/issues/3037.  What is being done here is all the way at the bottom and best that can be done for maven currently.

[pom] Add byte-buddy directly as a java agent

---

pom.xml
src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/main/java/net/masterthought/cucumber/ReportParser.java
src/main/java/net/masterthought/cucumber/generators/AbstractPage.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java
src/test/java/net/masterthought/cucumber/ReportGenerator.java
src/test/resources/simplelogger.properties

* commons-logging has come back to life but older products are likely long off from supporting and it does more to just redirect to slf4j and log4j2 then any other actual reason for existing.  Since slf4j was already a transient of this project, just make use of slf4j directly and exclude commons logging entirely.  Code itself wasn't using that either really but rather java util logger.
Tests manipulating logs appeared to me as being done to make less output show up on the console, achieved the same thing by simply using slf4j-simple in test scope and changing what gets printed out.

Use only slf4j (excluding legacy commons-logging*) and remove logging manipulations during tests as not needed.

---

.github/workflows/github-pages.yml

While the GH Pages upload shows a warning, it is also running this needlessly on forks to that point and shows green.  This will prevent it from running at all so job appropriately shows disabled on forks.

[GHA] Do not run github-pages unless on main repo

---

src/main/java/net/masterthought/cucumber/ReportBuilder.java
src/test/java/net/masterthought/cucumber/ReportBuilderTest.java

This pull request adds getter and setter methods for reportParser field with an overloaded constructor so that developers can extend the functionality of `ReportBuilder` with their own parsers, which provides greater flexibility for customized report processing.
1. Changed `reportParser` from `private final` to `private`, 
2. Add getter and setter methods for `reportParser`.
3. Added unit test
In projects that require customized parsing behavior, developers may want to extend `ReportParser` with additional functionality. Adjusting the visibility of `reportParser` facilitates these extensions while maintaining the original functionality of `ReportBuilder`.
Verified that existing functionality remains unaffected after the changes.
Confirmed that a custom parser can now be added by sub …

Change the visibility of the reportParser field

---

.github/workflows/sonarcloud.yml

currently this runs on every fork then fails as it should not have been run, this corrects the issue so that it only runs on the upstream repo here as expected.

[GHA] Do not run sonarcloud on forks

---

pom.xml

rest was already in here from really old obsolete oss parent.

[pom] Remove oss-parent, update libs, and add release/enforcer plugin
